// Code generated by ent, DO NOT EDIT.

package flightstatistic

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the flightstatistic type in the database.
	Label = "flight_statistic"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTotalThermicTime holds the string denoting the totalthermictime field in the database.
	FieldTotalThermicTime = "total_thermic_time"
	// FieldTotalFlightTime holds the string denoting the totalflighttime field in the database.
	FieldTotalFlightTime = "total_flight_time"
	// FieldMaxClimb holds the string denoting the maxclimb field in the database.
	FieldMaxClimb = "max_climb"
	// FieldMaxClimbRate holds the string denoting the maxclimbrate field in the database.
	FieldMaxClimbRate = "max_climb_rate"
	// FieldTotalClimb holds the string denoting the totalclimb field in the database.
	FieldTotalClimb = "total_climb"
	// FieldAverageClimbRate holds the string denoting the averageclimbrate field in the database.
	FieldAverageClimbRate = "average_climb_rate"
	// FieldNumberOfThermals holds the string denoting the numberofthermals field in the database.
	FieldNumberOfThermals = "number_of_thermals"
	// FieldPercentageThermic holds the string denoting the percentagethermic field in the database.
	FieldPercentageThermic = "percentage_thermic"
	// FieldMaxAltitude holds the string denoting the maxaltitude field in the database.
	FieldMaxAltitude = "max_altitude"
	// FieldTotalDistance holds the string denoting the totaldistance field in the database.
	FieldTotalDistance = "total_distance"
	// EdgeFlight holds the string denoting the flight edge name in mutations.
	EdgeFlight = "flight"
	// Table holds the table name of the flightstatistic in the database.
	Table = "flight_statistics"
	// FlightTable is the table that holds the flight relation/edge.
	FlightTable = "flight_statistics"
	// FlightInverseTable is the table name for the Flight entity.
	// It exists in this package in order to avoid circular dependency with the "flight" package.
	FlightInverseTable = "flights"
	// FlightColumn is the table column denoting the flight relation/edge.
	FlightColumn = "flight_statistic"
)

// Columns holds all SQL columns for flightstatistic fields.
var Columns = []string{
	FieldID,
	FieldTotalThermicTime,
	FieldTotalFlightTime,
	FieldMaxClimb,
	FieldMaxClimbRate,
	FieldTotalClimb,
	FieldAverageClimbRate,
	FieldNumberOfThermals,
	FieldPercentageThermic,
	FieldMaxAltitude,
	FieldTotalDistance,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "flight_statistics"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"flight_statistic",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the FlightStatistic queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTotalThermicTime orders the results by the totalThermicTime field.
func ByTotalThermicTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalThermicTime, opts...).ToFunc()
}

// ByTotalFlightTime orders the results by the totalFlightTime field.
func ByTotalFlightTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalFlightTime, opts...).ToFunc()
}

// ByMaxClimb orders the results by the maxClimb field.
func ByMaxClimb(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxClimb, opts...).ToFunc()
}

// ByMaxClimbRate orders the results by the maxClimbRate field.
func ByMaxClimbRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxClimbRate, opts...).ToFunc()
}

// ByTotalClimb orders the results by the totalClimb field.
func ByTotalClimb(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalClimb, opts...).ToFunc()
}

// ByAverageClimbRate orders the results by the averageClimbRate field.
func ByAverageClimbRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAverageClimbRate, opts...).ToFunc()
}

// ByNumberOfThermals orders the results by the numberOfThermals field.
func ByNumberOfThermals(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNumberOfThermals, opts...).ToFunc()
}

// ByPercentageThermic orders the results by the percentageThermic field.
func ByPercentageThermic(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPercentageThermic, opts...).ToFunc()
}

// ByMaxAltitude orders the results by the maxAltitude field.
func ByMaxAltitude(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxAltitude, opts...).ToFunc()
}

// ByTotalDistance orders the results by the totalDistance field.
func ByTotalDistance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalDistance, opts...).ToFunc()
}

// ByFlightField orders the results by flight field.
func ByFlightField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFlightStep(), sql.OrderByField(field, opts...))
	}
}
func newFlightStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FlightInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, FlightTable, FlightColumn),
	)
}
