// Code generated by ent, DO NOT EDIT.

package flightstatistic

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/AurelienS/cigare/internal/storage/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldLTE(FieldID, id))
}

// TotalThermicTime applies equality check predicate on the "totalThermicTime" field. It's identical to TotalThermicTimeEQ.
func TotalThermicTime(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldEQ(FieldTotalThermicTime, v))
}

// TotalFlightTime applies equality check predicate on the "totalFlightTime" field. It's identical to TotalFlightTimeEQ.
func TotalFlightTime(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldEQ(FieldTotalFlightTime, v))
}

// MaxClimb applies equality check predicate on the "maxClimb" field. It's identical to MaxClimbEQ.
func MaxClimb(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldEQ(FieldMaxClimb, v))
}

// MaxClimbRate applies equality check predicate on the "maxClimbRate" field. It's identical to MaxClimbRateEQ.
func MaxClimbRate(v float64) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldEQ(FieldMaxClimbRate, v))
}

// TotalClimb applies equality check predicate on the "totalClimb" field. It's identical to TotalClimbEQ.
func TotalClimb(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldEQ(FieldTotalClimb, v))
}

// AverageClimbRate applies equality check predicate on the "averageClimbRate" field. It's identical to AverageClimbRateEQ.
func AverageClimbRate(v float64) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldEQ(FieldAverageClimbRate, v))
}

// NumberOfThermals applies equality check predicate on the "numberOfThermals" field. It's identical to NumberOfThermalsEQ.
func NumberOfThermals(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldEQ(FieldNumberOfThermals, v))
}

// PercentageThermic applies equality check predicate on the "percentageThermic" field. It's identical to PercentageThermicEQ.
func PercentageThermic(v float64) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldEQ(FieldPercentageThermic, v))
}

// MaxAltitude applies equality check predicate on the "maxAltitude" field. It's identical to MaxAltitudeEQ.
func MaxAltitude(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldEQ(FieldMaxAltitude, v))
}

// TotalDistance applies equality check predicate on the "totalDistance" field. It's identical to TotalDistanceEQ.
func TotalDistance(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldEQ(FieldTotalDistance, v))
}

// GeoJSON applies equality check predicate on the "geoJSON" field. It's identical to GeoJSONEQ.
func GeoJSON(v string) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldEQ(FieldGeoJSON, v))
}

// TotalThermicTimeEQ applies the EQ predicate on the "totalThermicTime" field.
func TotalThermicTimeEQ(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldEQ(FieldTotalThermicTime, v))
}

// TotalThermicTimeNEQ applies the NEQ predicate on the "totalThermicTime" field.
func TotalThermicTimeNEQ(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldNEQ(FieldTotalThermicTime, v))
}

// TotalThermicTimeIn applies the In predicate on the "totalThermicTime" field.
func TotalThermicTimeIn(vs ...int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldIn(FieldTotalThermicTime, vs...))
}

// TotalThermicTimeNotIn applies the NotIn predicate on the "totalThermicTime" field.
func TotalThermicTimeNotIn(vs ...int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldNotIn(FieldTotalThermicTime, vs...))
}

// TotalThermicTimeGT applies the GT predicate on the "totalThermicTime" field.
func TotalThermicTimeGT(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldGT(FieldTotalThermicTime, v))
}

// TotalThermicTimeGTE applies the GTE predicate on the "totalThermicTime" field.
func TotalThermicTimeGTE(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldGTE(FieldTotalThermicTime, v))
}

// TotalThermicTimeLT applies the LT predicate on the "totalThermicTime" field.
func TotalThermicTimeLT(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldLT(FieldTotalThermicTime, v))
}

// TotalThermicTimeLTE applies the LTE predicate on the "totalThermicTime" field.
func TotalThermicTimeLTE(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldLTE(FieldTotalThermicTime, v))
}

// TotalFlightTimeEQ applies the EQ predicate on the "totalFlightTime" field.
func TotalFlightTimeEQ(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldEQ(FieldTotalFlightTime, v))
}

// TotalFlightTimeNEQ applies the NEQ predicate on the "totalFlightTime" field.
func TotalFlightTimeNEQ(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldNEQ(FieldTotalFlightTime, v))
}

// TotalFlightTimeIn applies the In predicate on the "totalFlightTime" field.
func TotalFlightTimeIn(vs ...int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldIn(FieldTotalFlightTime, vs...))
}

// TotalFlightTimeNotIn applies the NotIn predicate on the "totalFlightTime" field.
func TotalFlightTimeNotIn(vs ...int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldNotIn(FieldTotalFlightTime, vs...))
}

// TotalFlightTimeGT applies the GT predicate on the "totalFlightTime" field.
func TotalFlightTimeGT(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldGT(FieldTotalFlightTime, v))
}

// TotalFlightTimeGTE applies the GTE predicate on the "totalFlightTime" field.
func TotalFlightTimeGTE(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldGTE(FieldTotalFlightTime, v))
}

// TotalFlightTimeLT applies the LT predicate on the "totalFlightTime" field.
func TotalFlightTimeLT(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldLT(FieldTotalFlightTime, v))
}

// TotalFlightTimeLTE applies the LTE predicate on the "totalFlightTime" field.
func TotalFlightTimeLTE(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldLTE(FieldTotalFlightTime, v))
}

// MaxClimbEQ applies the EQ predicate on the "maxClimb" field.
func MaxClimbEQ(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldEQ(FieldMaxClimb, v))
}

// MaxClimbNEQ applies the NEQ predicate on the "maxClimb" field.
func MaxClimbNEQ(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldNEQ(FieldMaxClimb, v))
}

// MaxClimbIn applies the In predicate on the "maxClimb" field.
func MaxClimbIn(vs ...int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldIn(FieldMaxClimb, vs...))
}

// MaxClimbNotIn applies the NotIn predicate on the "maxClimb" field.
func MaxClimbNotIn(vs ...int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldNotIn(FieldMaxClimb, vs...))
}

// MaxClimbGT applies the GT predicate on the "maxClimb" field.
func MaxClimbGT(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldGT(FieldMaxClimb, v))
}

// MaxClimbGTE applies the GTE predicate on the "maxClimb" field.
func MaxClimbGTE(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldGTE(FieldMaxClimb, v))
}

// MaxClimbLT applies the LT predicate on the "maxClimb" field.
func MaxClimbLT(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldLT(FieldMaxClimb, v))
}

// MaxClimbLTE applies the LTE predicate on the "maxClimb" field.
func MaxClimbLTE(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldLTE(FieldMaxClimb, v))
}

// MaxClimbRateEQ applies the EQ predicate on the "maxClimbRate" field.
func MaxClimbRateEQ(v float64) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldEQ(FieldMaxClimbRate, v))
}

// MaxClimbRateNEQ applies the NEQ predicate on the "maxClimbRate" field.
func MaxClimbRateNEQ(v float64) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldNEQ(FieldMaxClimbRate, v))
}

// MaxClimbRateIn applies the In predicate on the "maxClimbRate" field.
func MaxClimbRateIn(vs ...float64) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldIn(FieldMaxClimbRate, vs...))
}

// MaxClimbRateNotIn applies the NotIn predicate on the "maxClimbRate" field.
func MaxClimbRateNotIn(vs ...float64) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldNotIn(FieldMaxClimbRate, vs...))
}

// MaxClimbRateGT applies the GT predicate on the "maxClimbRate" field.
func MaxClimbRateGT(v float64) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldGT(FieldMaxClimbRate, v))
}

// MaxClimbRateGTE applies the GTE predicate on the "maxClimbRate" field.
func MaxClimbRateGTE(v float64) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldGTE(FieldMaxClimbRate, v))
}

// MaxClimbRateLT applies the LT predicate on the "maxClimbRate" field.
func MaxClimbRateLT(v float64) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldLT(FieldMaxClimbRate, v))
}

// MaxClimbRateLTE applies the LTE predicate on the "maxClimbRate" field.
func MaxClimbRateLTE(v float64) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldLTE(FieldMaxClimbRate, v))
}

// TotalClimbEQ applies the EQ predicate on the "totalClimb" field.
func TotalClimbEQ(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldEQ(FieldTotalClimb, v))
}

// TotalClimbNEQ applies the NEQ predicate on the "totalClimb" field.
func TotalClimbNEQ(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldNEQ(FieldTotalClimb, v))
}

// TotalClimbIn applies the In predicate on the "totalClimb" field.
func TotalClimbIn(vs ...int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldIn(FieldTotalClimb, vs...))
}

// TotalClimbNotIn applies the NotIn predicate on the "totalClimb" field.
func TotalClimbNotIn(vs ...int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldNotIn(FieldTotalClimb, vs...))
}

// TotalClimbGT applies the GT predicate on the "totalClimb" field.
func TotalClimbGT(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldGT(FieldTotalClimb, v))
}

// TotalClimbGTE applies the GTE predicate on the "totalClimb" field.
func TotalClimbGTE(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldGTE(FieldTotalClimb, v))
}

// TotalClimbLT applies the LT predicate on the "totalClimb" field.
func TotalClimbLT(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldLT(FieldTotalClimb, v))
}

// TotalClimbLTE applies the LTE predicate on the "totalClimb" field.
func TotalClimbLTE(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldLTE(FieldTotalClimb, v))
}

// AverageClimbRateEQ applies the EQ predicate on the "averageClimbRate" field.
func AverageClimbRateEQ(v float64) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldEQ(FieldAverageClimbRate, v))
}

// AverageClimbRateNEQ applies the NEQ predicate on the "averageClimbRate" field.
func AverageClimbRateNEQ(v float64) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldNEQ(FieldAverageClimbRate, v))
}

// AverageClimbRateIn applies the In predicate on the "averageClimbRate" field.
func AverageClimbRateIn(vs ...float64) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldIn(FieldAverageClimbRate, vs...))
}

// AverageClimbRateNotIn applies the NotIn predicate on the "averageClimbRate" field.
func AverageClimbRateNotIn(vs ...float64) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldNotIn(FieldAverageClimbRate, vs...))
}

// AverageClimbRateGT applies the GT predicate on the "averageClimbRate" field.
func AverageClimbRateGT(v float64) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldGT(FieldAverageClimbRate, v))
}

// AverageClimbRateGTE applies the GTE predicate on the "averageClimbRate" field.
func AverageClimbRateGTE(v float64) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldGTE(FieldAverageClimbRate, v))
}

// AverageClimbRateLT applies the LT predicate on the "averageClimbRate" field.
func AverageClimbRateLT(v float64) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldLT(FieldAverageClimbRate, v))
}

// AverageClimbRateLTE applies the LTE predicate on the "averageClimbRate" field.
func AverageClimbRateLTE(v float64) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldLTE(FieldAverageClimbRate, v))
}

// NumberOfThermalsEQ applies the EQ predicate on the "numberOfThermals" field.
func NumberOfThermalsEQ(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldEQ(FieldNumberOfThermals, v))
}

// NumberOfThermalsNEQ applies the NEQ predicate on the "numberOfThermals" field.
func NumberOfThermalsNEQ(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldNEQ(FieldNumberOfThermals, v))
}

// NumberOfThermalsIn applies the In predicate on the "numberOfThermals" field.
func NumberOfThermalsIn(vs ...int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldIn(FieldNumberOfThermals, vs...))
}

// NumberOfThermalsNotIn applies the NotIn predicate on the "numberOfThermals" field.
func NumberOfThermalsNotIn(vs ...int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldNotIn(FieldNumberOfThermals, vs...))
}

// NumberOfThermalsGT applies the GT predicate on the "numberOfThermals" field.
func NumberOfThermalsGT(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldGT(FieldNumberOfThermals, v))
}

// NumberOfThermalsGTE applies the GTE predicate on the "numberOfThermals" field.
func NumberOfThermalsGTE(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldGTE(FieldNumberOfThermals, v))
}

// NumberOfThermalsLT applies the LT predicate on the "numberOfThermals" field.
func NumberOfThermalsLT(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldLT(FieldNumberOfThermals, v))
}

// NumberOfThermalsLTE applies the LTE predicate on the "numberOfThermals" field.
func NumberOfThermalsLTE(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldLTE(FieldNumberOfThermals, v))
}

// PercentageThermicEQ applies the EQ predicate on the "percentageThermic" field.
func PercentageThermicEQ(v float64) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldEQ(FieldPercentageThermic, v))
}

// PercentageThermicNEQ applies the NEQ predicate on the "percentageThermic" field.
func PercentageThermicNEQ(v float64) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldNEQ(FieldPercentageThermic, v))
}

// PercentageThermicIn applies the In predicate on the "percentageThermic" field.
func PercentageThermicIn(vs ...float64) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldIn(FieldPercentageThermic, vs...))
}

// PercentageThermicNotIn applies the NotIn predicate on the "percentageThermic" field.
func PercentageThermicNotIn(vs ...float64) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldNotIn(FieldPercentageThermic, vs...))
}

// PercentageThermicGT applies the GT predicate on the "percentageThermic" field.
func PercentageThermicGT(v float64) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldGT(FieldPercentageThermic, v))
}

// PercentageThermicGTE applies the GTE predicate on the "percentageThermic" field.
func PercentageThermicGTE(v float64) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldGTE(FieldPercentageThermic, v))
}

// PercentageThermicLT applies the LT predicate on the "percentageThermic" field.
func PercentageThermicLT(v float64) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldLT(FieldPercentageThermic, v))
}

// PercentageThermicLTE applies the LTE predicate on the "percentageThermic" field.
func PercentageThermicLTE(v float64) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldLTE(FieldPercentageThermic, v))
}

// MaxAltitudeEQ applies the EQ predicate on the "maxAltitude" field.
func MaxAltitudeEQ(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldEQ(FieldMaxAltitude, v))
}

// MaxAltitudeNEQ applies the NEQ predicate on the "maxAltitude" field.
func MaxAltitudeNEQ(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldNEQ(FieldMaxAltitude, v))
}

// MaxAltitudeIn applies the In predicate on the "maxAltitude" field.
func MaxAltitudeIn(vs ...int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldIn(FieldMaxAltitude, vs...))
}

// MaxAltitudeNotIn applies the NotIn predicate on the "maxAltitude" field.
func MaxAltitudeNotIn(vs ...int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldNotIn(FieldMaxAltitude, vs...))
}

// MaxAltitudeGT applies the GT predicate on the "maxAltitude" field.
func MaxAltitudeGT(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldGT(FieldMaxAltitude, v))
}

// MaxAltitudeGTE applies the GTE predicate on the "maxAltitude" field.
func MaxAltitudeGTE(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldGTE(FieldMaxAltitude, v))
}

// MaxAltitudeLT applies the LT predicate on the "maxAltitude" field.
func MaxAltitudeLT(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldLT(FieldMaxAltitude, v))
}

// MaxAltitudeLTE applies the LTE predicate on the "maxAltitude" field.
func MaxAltitudeLTE(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldLTE(FieldMaxAltitude, v))
}

// TotalDistanceEQ applies the EQ predicate on the "totalDistance" field.
func TotalDistanceEQ(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldEQ(FieldTotalDistance, v))
}

// TotalDistanceNEQ applies the NEQ predicate on the "totalDistance" field.
func TotalDistanceNEQ(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldNEQ(FieldTotalDistance, v))
}

// TotalDistanceIn applies the In predicate on the "totalDistance" field.
func TotalDistanceIn(vs ...int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldIn(FieldTotalDistance, vs...))
}

// TotalDistanceNotIn applies the NotIn predicate on the "totalDistance" field.
func TotalDistanceNotIn(vs ...int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldNotIn(FieldTotalDistance, vs...))
}

// TotalDistanceGT applies the GT predicate on the "totalDistance" field.
func TotalDistanceGT(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldGT(FieldTotalDistance, v))
}

// TotalDistanceGTE applies the GTE predicate on the "totalDistance" field.
func TotalDistanceGTE(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldGTE(FieldTotalDistance, v))
}

// TotalDistanceLT applies the LT predicate on the "totalDistance" field.
func TotalDistanceLT(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldLT(FieldTotalDistance, v))
}

// TotalDistanceLTE applies the LTE predicate on the "totalDistance" field.
func TotalDistanceLTE(v int) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldLTE(FieldTotalDistance, v))
}

// GeoJSONEQ applies the EQ predicate on the "geoJSON" field.
func GeoJSONEQ(v string) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldEQ(FieldGeoJSON, v))
}

// GeoJSONNEQ applies the NEQ predicate on the "geoJSON" field.
func GeoJSONNEQ(v string) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldNEQ(FieldGeoJSON, v))
}

// GeoJSONIn applies the In predicate on the "geoJSON" field.
func GeoJSONIn(vs ...string) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldIn(FieldGeoJSON, vs...))
}

// GeoJSONNotIn applies the NotIn predicate on the "geoJSON" field.
func GeoJSONNotIn(vs ...string) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldNotIn(FieldGeoJSON, vs...))
}

// GeoJSONGT applies the GT predicate on the "geoJSON" field.
func GeoJSONGT(v string) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldGT(FieldGeoJSON, v))
}

// GeoJSONGTE applies the GTE predicate on the "geoJSON" field.
func GeoJSONGTE(v string) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldGTE(FieldGeoJSON, v))
}

// GeoJSONLT applies the LT predicate on the "geoJSON" field.
func GeoJSONLT(v string) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldLT(FieldGeoJSON, v))
}

// GeoJSONLTE applies the LTE predicate on the "geoJSON" field.
func GeoJSONLTE(v string) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldLTE(FieldGeoJSON, v))
}

// GeoJSONContains applies the Contains predicate on the "geoJSON" field.
func GeoJSONContains(v string) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldContains(FieldGeoJSON, v))
}

// GeoJSONHasPrefix applies the HasPrefix predicate on the "geoJSON" field.
func GeoJSONHasPrefix(v string) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldHasPrefix(FieldGeoJSON, v))
}

// GeoJSONHasSuffix applies the HasSuffix predicate on the "geoJSON" field.
func GeoJSONHasSuffix(v string) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldHasSuffix(FieldGeoJSON, v))
}

// GeoJSONEqualFold applies the EqualFold predicate on the "geoJSON" field.
func GeoJSONEqualFold(v string) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldEqualFold(FieldGeoJSON, v))
}

// GeoJSONContainsFold applies the ContainsFold predicate on the "geoJSON" field.
func GeoJSONContainsFold(v string) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.FieldContainsFold(FieldGeoJSON, v))
}

// HasFlight applies the HasEdge predicate on the "flight" edge.
func HasFlight() predicate.FlightStatistic {
	return predicate.FlightStatistic(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, FlightTable, FlightColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFlightWith applies the HasEdge predicate on the "flight" edge with a given conditions (other predicates).
func HasFlightWith(preds ...predicate.Flight) predicate.FlightStatistic {
	return predicate.FlightStatistic(func(s *sql.Selector) {
		step := newFlightStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FlightStatistic) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FlightStatistic) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FlightStatistic) predicate.FlightStatistic {
	return predicate.FlightStatistic(sql.NotPredicates(p))
}
