// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.513
package chart

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/AurelienS/cigare/web/viewmodel"

func setupBarCount(data viewmodel.ChartData, id string, yearDateOnly bool) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_setupBarCount_ac1d`,
		Function: `function __templ_setupBarCount_ac1d(data, id, yearDateOnly){const ctx = document.getElementById(id).getContext('2d');

    const scaleConfig = {
        y: {
            beginAtZero: true,
            grid: { display: false },
            title: {
                display: true,
                text: 'Heures',
            },
        },
        x: {
            grid: { display: false }
        }
    }
    const legendConfig = {
        display: data.Datasets.length > 1,
        position: 'left',
    };

    const tooltipConfig = {
        mode: 'index',
        intersect: false,
        callbacks: {}
    };

    const animationConfig = { duration: 1000 };

    const options = {
        responsive: true,
        maintainAspectRatio: false,
        scales: scaleConfig,
        plugins: {
            legend: legendConfig,
            tooltip: tooltipConfig
        },
        animation: animationConfig
    };

    const chartData = {
        labels: yearDateOnly ? data.Labels.map(l => l.slice(-4)) : data.Labels,
        datasets: data.Datasets.map((ds, index) => ({
            label:ds.Label,
            data: ds.Data,
            backgroundColor: ds.Color,
            borderColor: ds.Color,
            borderWidth: 1,
            borderRadius: 0,
            hidden: index > 1,
            barThickness: 12,
        }))
    };

    new Chart(ctx, {
        type: 'bar',
        data: chartData,
        options: options
    });}`,
		Call:       templ.SafeScript(`__templ_setupBarCount_ac1d`, data, id, yearDateOnly),
		CallInline: templ.SafeScriptInline(`__templ_setupBarCount_ac1d`, data, id, yearDateOnly),
	}
}

func BarCount(data viewmodel.ChartData, id string, yearDateOnly bool) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"h-full w-full\"><canvas id=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(id))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\"></canvas>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = setupBarCount(data, id, yearDateOnly).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
