// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.513
package chart

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/AurelienS/cigare/web/viewmodel"

func setupLine(data viewmodel.ChartData, id string, unit string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_setupLine_3b10`,
		Function: `function __templ_setupLine_3b10(data, id, unit){const ctx = document.getElementById(id).getContext('2d');

    const scalesConfig = {
        y: {
            grid: { display: false },
            title: {
                display: true,
                text: unit,
            },
        },
        x: {
            grid: { display: false }
        }
    };

    const pluginsConfig = {
        legend: { display: false },
        tooltip: {
            mode: 'index',
            intersect: false,
            callbacks: {}
        }
    };

    const animationConfig = { duration: 1000 };

    const chartOptions = {
        responsive: true,
        maintainAspectRatio: false,
        scales: scalesConfig,
        plugins: pluginsConfig,
        animation: animationConfig
    };

    const chartData = {
        labels: data.Labels,
        datasets: data.Datasets.map((ds, index) => ({
            label:ds.Label,
            data: ds.Data,
            backgroundColor: ds.Color,
            borderColor: ds.Color,
            borderWidth: 1,
            borderRadius: 0,
            hidden: index > 1,
            barThickness: 12,
        }))
    };

    new Chart(ctx, {
        type: 'line',
        data: chartData,
        options: chartOptions
    });}`,
		Call:       templ.SafeScript(`__templ_setupLine_3b10`, data, id, unit),
		CallInline: templ.SafeScriptInline(`__templ_setupLine_3b10`, data, id, unit),
	}
}

func Line(data viewmodel.ChartData, id string, unit string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"h-full w-full\"><canvas id=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(id))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\"></canvas>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = setupLine(data, id, unit).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
