// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: flight_statistic.sql

package storage

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertFlightStats = `-- name: InsertFlightStats :one
INSERT INTO flight_statistics (
    total_thermic_time,
    total_flight_time,
    max_climb,
    max_climb_rate,
    total_climb,
    average_climb_rate,
    number_of_thermals,
    percentage_thermic,
    max_altitude
  )
VALUES
  (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
  ) RETURNING id
`

type InsertFlightStatsParams struct {
	TotalThermicTime  pgtype.Interval
	TotalFlightTime   pgtype.Interval
	MaxClimb          int32
	MaxClimbRate      float64
	TotalClimb        int32
	AverageClimbRate  float64
	NumberOfThermals  int32
	PercentageThermic float64
	MaxAltitude       int32
}

func (q *Queries) InsertFlightStats(ctx context.Context, arg InsertFlightStatsParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertFlightStats,
		arg.TotalThermicTime,
		arg.TotalFlightTime,
		arg.MaxClimb,
		arg.MaxClimbRate,
		arg.TotalClimb,
		arg.AverageClimbRate,
		arg.NumberOfThermals,
		arg.PercentageThermic,
		arg.MaxAltitude,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
