// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package storage

import (
	"database/sql"
	"time"
)

type Flight struct {
	ID                 int32
	Date               time.Time
	TakeoffLocation    string
	IgcFilePath        string
	UserID             int32
	GliderID           int32
	FlightStatisticsID sql.NullInt32
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type FlightStatistic struct {
	ID                int32
	TotalThermicTime  int64
	TotalFlightTime   int64
	MaxClimb          int32
	MaxClimbRate      float64
	TotalClimb        int32
	AverageClimbRate  float64
	NumberOfThermals  int32
	PercentageThermic float64
	MaxAltitude       int32
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type Glider struct {
	ID        int32
	Name      string
	UserID    int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID         int32
	GoogleID   string
	Email      string
	Name       string
	PictureUrl string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
