// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package storage

import (
	"github.com/jackc/pgx/v5/pgtype"
	"time"
)

type Flight struct {
	ID                 int32
	Date               pgtype.Timestamptz
	TakeoffLocation    string
	IgcFilePath        string
	UserID             int32
	FlightStatisticsID int32
}

type FlightStatistic struct {
	ID                int32
	TotalThermicTime  time.Duration
	TotalFlightTime   time.Duration
	MaxClimb          int32
	MaxClimbRate      float64
	TotalClimb        int32
	AverageClimbRate  float64
	NumberOfThermals  int32
	PercentageThermic float64
	MaxAltitude       int32
}

type Squad struct {
	ID        int32
	Name      string
	CreatedAt pgtype.Timestamptz
}

type SquadMember struct {
	ID       int32
	SquadID  int32
	UserID   int32
	Admin    pgtype.Bool
	JoinedAt pgtype.Timestamptz
}

type User struct {
	ID         int32
	GoogleID   string
	Email      string
	Name       string
	PictureUrl string
	CreatedAt  pgtype.Timestamptz
}
