DROP TABLE IF EXISTS flights CASCADE;

DROP TABLE IF EXISTS gliders CASCADE;

DROP TABLE IF EXISTS flight_statistics CASCADE;

DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  google_id VARCHAR(255) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  picture_url VARCHAR(255) NOT NULL,
  default_glider_id INT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE gliders (
  id serial primary key,
  NAME VARCHAR(255) NOT NULL,
  user_id INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER TABLE
  gliders
ADD
  FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE
  users
ADD
  FOREIGN KEY (default_glider_id) REFERENCES gliders(id);

CREATE TABLE flight_statistics (
  id SERIAL PRIMARY KEY,
  total_thermic_time INTERVAL NOT NULL,
  total_flight_time INTERVAL NOT NULL,
  max_climb INTEGER NOT NULL,
  max_climb_rate FLOAT NOT NULL,
  total_climb INTEGER NOT NULL,
  average_climb_rate FLOAT NOT NULL,
  number_of_thermals INTEGER NOT NULL,
  percentage_thermic FLOAT NOT NULL,
  max_altitude INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE flights (
  id SERIAL PRIMARY KEY,
  DATE TIMESTAMP WITH TIME ZONE NOT NULL,
  takeoff_location VARCHAR(255) NOT NULL,
  igc_file_path TEXT NOT NULL,
  user_id INTEGER NOT NULL,
  glider_id INTEGER NOT NULL,
  flight_statistics_id INTEGER NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (glider_id) REFERENCES gliders(id),
  FOREIGN KEY (flight_statistics_id) REFERENCES flight_statistics(id)
);
