DROP TABLE IF EXISTS flights CASCADE;
DROP TABLE IF EXISTS flight_statistics CASCADE;
DROP TABLE IF EXISTS squad_members CASCADE;
DROP TABLE IF EXISTS squads CASCADE;
DROP TABLE IF EXISTS users CASCADE;


CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  google_id VARCHAR(255) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  picture_url VARCHAR(255) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE flight_statistics (
  id SERIAL PRIMARY KEY,
  total_thermic_time INTERVAL NOT NULL,
  total_flight_time INTERVAL NOT NULL,
  max_climb INTEGER NOT NULL,
  max_climb_rate FLOAT NOT NULL,
  total_climb INTEGER NOT NULL,
  average_climb_rate FLOAT NOT NULL,
  number_of_thermals INTEGER NOT NULL,
  percentage_thermic FLOAT NOT NULL,
  max_altitude INTEGER NOT NULL
);

CREATE TABLE flights (
  id SERIAL PRIMARY KEY,
  DATE TIMESTAMP WITH TIME ZONE NOT NULL,
  takeoff_location VARCHAR(255) NOT NULL,
  igc_file_path TEXT NOT NULL,
  user_id INTEGER NOT NULL,
  flight_statistics_id INTEGER NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON
  DELETE
    CASCADE,
    FOREIGN KEY (flight_statistics_id) REFERENCES flight_statistics(id) ON
  DELETE
    CASCADE
);

CREATE TABLE squads (
  id SERIAL PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE squad_members (
  id SERIAL PRIMARY KEY,
  squad_id INT NOT NULL,
  user_id INT NOT NULL,
  admin BOOLEAN DEFAULT FALSE,
  joined_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  FOREIGN KEY (squad_id) REFERENCES squads(id) ON
  DELETE
    CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON
  DELETE
    CASCADE,
    UNIQUE (squad_id, user_id)
);