// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: squad.sql

package storage

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findAllSquadForUser = `-- name: FindAllSquadForUser :many
SELECT
    s.id, s.name, s.created_at
FROM squads s
    JOIN squad_members sm ON s.id = sm.squad_id
WHERE
    sm.user_id = $1
`

func (q *Queries) FindAllSquadForUser(ctx context.Context, userID int32) ([]Squad, error) {
	rows, err := q.db.Query(ctx, findAllSquadForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Squad
	for rows.Next() {
		var i Squad
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSquad = `-- name: InsertSquad :one
INSERT INTO squads (NAME)
VALUES
    ($1) RETURNING id, name, created_at
`

func (q *Queries) InsertSquad(ctx context.Context, name string) (Squad, error) {
	row := q.db.QueryRow(ctx, insertSquad, name)
	var i Squad
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const insertSquadMember = `-- name: InsertSquadMember :exec
INSERT INTO squad_members (squad_id, user_id, admin, joined_at)
VALUES
    ($1, $2, $3, NOW())
`

type InsertSquadMemberParams struct {
	SquadID int32
	UserID  int32
	Admin   pgtype.Bool
}

func (q *Queries) InsertSquadMember(ctx context.Context, arg InsertSquadMemberParams) error {
	_, err := q.db.Exec(ctx, insertSquadMember, arg.SquadID, arg.UserID, arg.Admin)
	return err
}
