// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: user.sql

package storage

import (
	"context"
)

const getUserWithGoogleId = `-- name: GetUserWithGoogleId :one
SELECT
  id, google_id, email, name, picture_url, created_at
FROM users
WHERE
  google_id = $1
LIMIT 1
`

func (q *Queries) GetUserWithGoogleId(ctx context.Context, googleID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserWithGoogleId, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Name,
		&i.PictureUrl,
		&i.CreatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (
    google_id,
    email,
    NAME,
    picture_url
  )
VALUES
  ($1, $2, $3, $4) ON CONFLICT (google_id) DO
UPDATE
SET
  email = EXCLUDED.email,
  NAME = EXCLUDED.name,
  picture_url = EXCLUDED.picture_url RETURNING id, google_id, email, name, picture_url, created_at
`

type UpsertUserParams struct {
	GoogleID   string
	Email      string
	Name       string
	PictureUrl string
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.GoogleID,
		arg.Email,
		arg.Name,
		arg.PictureUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Name,
		&i.PictureUrl,
		&i.CreatedAt,
	)
	return i, err
}
