// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.513
package page

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/AurelienS/cigare/web/template/layout"
import "github.com/AurelienS/cigare/internal/model"
import view "github.com/AurelienS/cigare/web/template/flight"
import "strconv"
import "github.com/AurelienS/cigare/web/template/component"

func getFlightCOunt(flights []model.Flight) string {
	return strconv.Itoa(len(flights))
}

var data = []component.StatView{
	{
		Title:       "Altitude",
		Icon:        "🏔️",
		NoRank:      true,
		Description: "",
		Categories: []component.StatCategory{
			{Title: "min", Value: "112 m"},
			{Title: "max", Value: "1552 m"},
		},
	},
	{
		Title:       "Variomètre",
		Icon:        "📈",
		NoRank:      true,
		Description: "",
		Categories: []component.StatCategory{
			{Title: "min", Value: "-16 m/s"},
			{Title: "max", Value: "+6 m/s"},
		},
	},
	{
		Title:       "Vitesse",
		Icon:        "🏎️",
		NoRank:      true,
		Description: "",
		Categories: []component.StatCategory{
			{Title: "max", Value: "70 km/h"},
		},
	},
	{
		Title:       "Durée de vol",
		Icon:        "⏱️",
		NoRank:      true,
		Description: "",
		Categories: []component.StatCategory{
			{Title: "min", Value: "2'"},
			{Title: "max", Value: "4h"},
		},
	},
	{
		Title:       "Durée de vol moyen",
		Icon:        "⏱️",
		NoRank:      true,
		Description: "",
		Categories: []component.StatCategory{
			{Title: "", Value: "20min"},
			{Title: "30j", Value: "40min"},
			{Title: "365j", Value: "25min"},
		},
	},
	{
		Title:       "Nombre de vol",
		Icon:        "⏱️",
		NoRank:      true,
		Description: "",
		Categories: []component.StatCategory{
			{Title: "", Value: "20"},
			{Title: "30j", Value: "40"},
			{Title: "365j", Value: "25"},
		},
	},
	{
		Title:       "Temps de vol",
		Icon:        "⏱️",
		NoRank:      true,
		Description: "",
		Categories: []component.StatCategory{
			{Title: "", Value: "20h"},
			{Title: "30j", Value: "40h"},
			{Title: "365j", Value: "25h"},
		},
	},
}

func Flights(arg view.DashboardView) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"avatar\"><div class=\"w-24 mask mask-squircle\"><img src=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(arg.Img))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\"></div></div><div class=\"flex flex-col justify-between\" id=\"flightPage\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = view.UploadFlightForm("/flight", "uploadForm").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"flex flex-wrap gap-4\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, d := range data {
				templ_7745c5c3_Err = component.StatCard(d).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = view.FlightRecords(arg.Flights).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layout.Base(arg.User).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
