// Code generated by ent, DO NOT EDIT.

package flight

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/AurelienS/airtime/internal/storage/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Flight {
	return predicate.Flight(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Flight {
	return predicate.Flight(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Flight {
	return predicate.Flight(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Flight {
	return predicate.Flight(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Flight {
	return predicate.Flight(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Flight {
	return predicate.Flight(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Flight {
	return predicate.Flight(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Flight {
	return predicate.Flight(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Flight {
	return predicate.Flight(sql.FieldLTE(FieldID, id))
}

// Date applies equality check predicate on the "date" field. It's identical to DateEQ.
func Date(v time.Time) predicate.Flight {
	return predicate.Flight(sql.FieldEQ(FieldDate, v))
}

// Location applies equality check predicate on the "location" field. It's identical to LocationEQ.
func Location(v string) predicate.Flight {
	return predicate.Flight(sql.FieldEQ(FieldLocation, v))
}

// Duration applies equality check predicate on the "duration" field. It's identical to DurationEQ.
func Duration(v int) predicate.Flight {
	return predicate.Flight(sql.FieldEQ(FieldDuration, v))
}

// Distance applies equality check predicate on the "distance" field. It's identical to DistanceEQ.
func Distance(v int) predicate.Flight {
	return predicate.Flight(sql.FieldEQ(FieldDistance, v))
}

// AltitudeMax applies equality check predicate on the "altitudeMax" field. It's identical to AltitudeMaxEQ.
func AltitudeMax(v int) predicate.Flight {
	return predicate.Flight(sql.FieldEQ(FieldAltitudeMax, v))
}

// IgcData applies equality check predicate on the "igcData" field. It's identical to IgcDataEQ.
func IgcData(v string) predicate.Flight {
	return predicate.Flight(sql.FieldEQ(FieldIgcData, v))
}

// DateEQ applies the EQ predicate on the "date" field.
func DateEQ(v time.Time) predicate.Flight {
	return predicate.Flight(sql.FieldEQ(FieldDate, v))
}

// DateNEQ applies the NEQ predicate on the "date" field.
func DateNEQ(v time.Time) predicate.Flight {
	return predicate.Flight(sql.FieldNEQ(FieldDate, v))
}

// DateIn applies the In predicate on the "date" field.
func DateIn(vs ...time.Time) predicate.Flight {
	return predicate.Flight(sql.FieldIn(FieldDate, vs...))
}

// DateNotIn applies the NotIn predicate on the "date" field.
func DateNotIn(vs ...time.Time) predicate.Flight {
	return predicate.Flight(sql.FieldNotIn(FieldDate, vs...))
}

// DateGT applies the GT predicate on the "date" field.
func DateGT(v time.Time) predicate.Flight {
	return predicate.Flight(sql.FieldGT(FieldDate, v))
}

// DateGTE applies the GTE predicate on the "date" field.
func DateGTE(v time.Time) predicate.Flight {
	return predicate.Flight(sql.FieldGTE(FieldDate, v))
}

// DateLT applies the LT predicate on the "date" field.
func DateLT(v time.Time) predicate.Flight {
	return predicate.Flight(sql.FieldLT(FieldDate, v))
}

// DateLTE applies the LTE predicate on the "date" field.
func DateLTE(v time.Time) predicate.Flight {
	return predicate.Flight(sql.FieldLTE(FieldDate, v))
}

// LocationEQ applies the EQ predicate on the "location" field.
func LocationEQ(v string) predicate.Flight {
	return predicate.Flight(sql.FieldEQ(FieldLocation, v))
}

// LocationNEQ applies the NEQ predicate on the "location" field.
func LocationNEQ(v string) predicate.Flight {
	return predicate.Flight(sql.FieldNEQ(FieldLocation, v))
}

// LocationIn applies the In predicate on the "location" field.
func LocationIn(vs ...string) predicate.Flight {
	return predicate.Flight(sql.FieldIn(FieldLocation, vs...))
}

// LocationNotIn applies the NotIn predicate on the "location" field.
func LocationNotIn(vs ...string) predicate.Flight {
	return predicate.Flight(sql.FieldNotIn(FieldLocation, vs...))
}

// LocationGT applies the GT predicate on the "location" field.
func LocationGT(v string) predicate.Flight {
	return predicate.Flight(sql.FieldGT(FieldLocation, v))
}

// LocationGTE applies the GTE predicate on the "location" field.
func LocationGTE(v string) predicate.Flight {
	return predicate.Flight(sql.FieldGTE(FieldLocation, v))
}

// LocationLT applies the LT predicate on the "location" field.
func LocationLT(v string) predicate.Flight {
	return predicate.Flight(sql.FieldLT(FieldLocation, v))
}

// LocationLTE applies the LTE predicate on the "location" field.
func LocationLTE(v string) predicate.Flight {
	return predicate.Flight(sql.FieldLTE(FieldLocation, v))
}

// LocationContains applies the Contains predicate on the "location" field.
func LocationContains(v string) predicate.Flight {
	return predicate.Flight(sql.FieldContains(FieldLocation, v))
}

// LocationHasPrefix applies the HasPrefix predicate on the "location" field.
func LocationHasPrefix(v string) predicate.Flight {
	return predicate.Flight(sql.FieldHasPrefix(FieldLocation, v))
}

// LocationHasSuffix applies the HasSuffix predicate on the "location" field.
func LocationHasSuffix(v string) predicate.Flight {
	return predicate.Flight(sql.FieldHasSuffix(FieldLocation, v))
}

// LocationEqualFold applies the EqualFold predicate on the "location" field.
func LocationEqualFold(v string) predicate.Flight {
	return predicate.Flight(sql.FieldEqualFold(FieldLocation, v))
}

// LocationContainsFold applies the ContainsFold predicate on the "location" field.
func LocationContainsFold(v string) predicate.Flight {
	return predicate.Flight(sql.FieldContainsFold(FieldLocation, v))
}

// DurationEQ applies the EQ predicate on the "duration" field.
func DurationEQ(v int) predicate.Flight {
	return predicate.Flight(sql.FieldEQ(FieldDuration, v))
}

// DurationNEQ applies the NEQ predicate on the "duration" field.
func DurationNEQ(v int) predicate.Flight {
	return predicate.Flight(sql.FieldNEQ(FieldDuration, v))
}

// DurationIn applies the In predicate on the "duration" field.
func DurationIn(vs ...int) predicate.Flight {
	return predicate.Flight(sql.FieldIn(FieldDuration, vs...))
}

// DurationNotIn applies the NotIn predicate on the "duration" field.
func DurationNotIn(vs ...int) predicate.Flight {
	return predicate.Flight(sql.FieldNotIn(FieldDuration, vs...))
}

// DurationGT applies the GT predicate on the "duration" field.
func DurationGT(v int) predicate.Flight {
	return predicate.Flight(sql.FieldGT(FieldDuration, v))
}

// DurationGTE applies the GTE predicate on the "duration" field.
func DurationGTE(v int) predicate.Flight {
	return predicate.Flight(sql.FieldGTE(FieldDuration, v))
}

// DurationLT applies the LT predicate on the "duration" field.
func DurationLT(v int) predicate.Flight {
	return predicate.Flight(sql.FieldLT(FieldDuration, v))
}

// DurationLTE applies the LTE predicate on the "duration" field.
func DurationLTE(v int) predicate.Flight {
	return predicate.Flight(sql.FieldLTE(FieldDuration, v))
}

// DistanceEQ applies the EQ predicate on the "distance" field.
func DistanceEQ(v int) predicate.Flight {
	return predicate.Flight(sql.FieldEQ(FieldDistance, v))
}

// DistanceNEQ applies the NEQ predicate on the "distance" field.
func DistanceNEQ(v int) predicate.Flight {
	return predicate.Flight(sql.FieldNEQ(FieldDistance, v))
}

// DistanceIn applies the In predicate on the "distance" field.
func DistanceIn(vs ...int) predicate.Flight {
	return predicate.Flight(sql.FieldIn(FieldDistance, vs...))
}

// DistanceNotIn applies the NotIn predicate on the "distance" field.
func DistanceNotIn(vs ...int) predicate.Flight {
	return predicate.Flight(sql.FieldNotIn(FieldDistance, vs...))
}

// DistanceGT applies the GT predicate on the "distance" field.
func DistanceGT(v int) predicate.Flight {
	return predicate.Flight(sql.FieldGT(FieldDistance, v))
}

// DistanceGTE applies the GTE predicate on the "distance" field.
func DistanceGTE(v int) predicate.Flight {
	return predicate.Flight(sql.FieldGTE(FieldDistance, v))
}

// DistanceLT applies the LT predicate on the "distance" field.
func DistanceLT(v int) predicate.Flight {
	return predicate.Flight(sql.FieldLT(FieldDistance, v))
}

// DistanceLTE applies the LTE predicate on the "distance" field.
func DistanceLTE(v int) predicate.Flight {
	return predicate.Flight(sql.FieldLTE(FieldDistance, v))
}

// AltitudeMaxEQ applies the EQ predicate on the "altitudeMax" field.
func AltitudeMaxEQ(v int) predicate.Flight {
	return predicate.Flight(sql.FieldEQ(FieldAltitudeMax, v))
}

// AltitudeMaxNEQ applies the NEQ predicate on the "altitudeMax" field.
func AltitudeMaxNEQ(v int) predicate.Flight {
	return predicate.Flight(sql.FieldNEQ(FieldAltitudeMax, v))
}

// AltitudeMaxIn applies the In predicate on the "altitudeMax" field.
func AltitudeMaxIn(vs ...int) predicate.Flight {
	return predicate.Flight(sql.FieldIn(FieldAltitudeMax, vs...))
}

// AltitudeMaxNotIn applies the NotIn predicate on the "altitudeMax" field.
func AltitudeMaxNotIn(vs ...int) predicate.Flight {
	return predicate.Flight(sql.FieldNotIn(FieldAltitudeMax, vs...))
}

// AltitudeMaxGT applies the GT predicate on the "altitudeMax" field.
func AltitudeMaxGT(v int) predicate.Flight {
	return predicate.Flight(sql.FieldGT(FieldAltitudeMax, v))
}

// AltitudeMaxGTE applies the GTE predicate on the "altitudeMax" field.
func AltitudeMaxGTE(v int) predicate.Flight {
	return predicate.Flight(sql.FieldGTE(FieldAltitudeMax, v))
}

// AltitudeMaxLT applies the LT predicate on the "altitudeMax" field.
func AltitudeMaxLT(v int) predicate.Flight {
	return predicate.Flight(sql.FieldLT(FieldAltitudeMax, v))
}

// AltitudeMaxLTE applies the LTE predicate on the "altitudeMax" field.
func AltitudeMaxLTE(v int) predicate.Flight {
	return predicate.Flight(sql.FieldLTE(FieldAltitudeMax, v))
}

// IgcDataEQ applies the EQ predicate on the "igcData" field.
func IgcDataEQ(v string) predicate.Flight {
	return predicate.Flight(sql.FieldEQ(FieldIgcData, v))
}

// IgcDataNEQ applies the NEQ predicate on the "igcData" field.
func IgcDataNEQ(v string) predicate.Flight {
	return predicate.Flight(sql.FieldNEQ(FieldIgcData, v))
}

// IgcDataIn applies the In predicate on the "igcData" field.
func IgcDataIn(vs ...string) predicate.Flight {
	return predicate.Flight(sql.FieldIn(FieldIgcData, vs...))
}

// IgcDataNotIn applies the NotIn predicate on the "igcData" field.
func IgcDataNotIn(vs ...string) predicate.Flight {
	return predicate.Flight(sql.FieldNotIn(FieldIgcData, vs...))
}

// IgcDataGT applies the GT predicate on the "igcData" field.
func IgcDataGT(v string) predicate.Flight {
	return predicate.Flight(sql.FieldGT(FieldIgcData, v))
}

// IgcDataGTE applies the GTE predicate on the "igcData" field.
func IgcDataGTE(v string) predicate.Flight {
	return predicate.Flight(sql.FieldGTE(FieldIgcData, v))
}

// IgcDataLT applies the LT predicate on the "igcData" field.
func IgcDataLT(v string) predicate.Flight {
	return predicate.Flight(sql.FieldLT(FieldIgcData, v))
}

// IgcDataLTE applies the LTE predicate on the "igcData" field.
func IgcDataLTE(v string) predicate.Flight {
	return predicate.Flight(sql.FieldLTE(FieldIgcData, v))
}

// IgcDataContains applies the Contains predicate on the "igcData" field.
func IgcDataContains(v string) predicate.Flight {
	return predicate.Flight(sql.FieldContains(FieldIgcData, v))
}

// IgcDataHasPrefix applies the HasPrefix predicate on the "igcData" field.
func IgcDataHasPrefix(v string) predicate.Flight {
	return predicate.Flight(sql.FieldHasPrefix(FieldIgcData, v))
}

// IgcDataHasSuffix applies the HasSuffix predicate on the "igcData" field.
func IgcDataHasSuffix(v string) predicate.Flight {
	return predicate.Flight(sql.FieldHasSuffix(FieldIgcData, v))
}

// IgcDataEqualFold applies the EqualFold predicate on the "igcData" field.
func IgcDataEqualFold(v string) predicate.Flight {
	return predicate.Flight(sql.FieldEqualFold(FieldIgcData, v))
}

// IgcDataContainsFold applies the ContainsFold predicate on the "igcData" field.
func IgcDataContainsFold(v string) predicate.Flight {
	return predicate.Flight(sql.FieldContainsFold(FieldIgcData, v))
}

// HasPilot applies the HasEdge predicate on the "pilot" edge.
func HasPilot() predicate.Flight {
	return predicate.Flight(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PilotTable, PilotColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPilotWith applies the HasEdge predicate on the "pilot" edge with a given conditions (other predicates).
func HasPilotWith(preds ...predicate.User) predicate.Flight {
	return predicate.Flight(func(s *sql.Selector) {
		step := newPilotStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Flight) predicate.Flight {
	return predicate.Flight(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Flight) predicate.Flight {
	return predicate.Flight(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Flight) predicate.Flight {
	return predicate.Flight(sql.NotPredicates(p))
}
