// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/AurelienS/cigare/internal/storage/ent/flight"
	"github.com/AurelienS/cigare/internal/storage/ent/flightstatistic"
	"github.com/AurelienS/cigare/internal/storage/ent/predicate"
)

// FlightStatisticUpdate is the builder for updating FlightStatistic entities.
type FlightStatisticUpdate struct {
	config
	hooks    []Hook
	mutation *FlightStatisticMutation
}

// Where appends a list predicates to the FlightStatisticUpdate builder.
func (fsu *FlightStatisticUpdate) Where(ps ...predicate.FlightStatistic) *FlightStatisticUpdate {
	fsu.mutation.Where(ps...)
	return fsu
}

// SetTotalThermicTime sets the "totalThermicTime" field.
func (fsu *FlightStatisticUpdate) SetTotalThermicTime(i int) *FlightStatisticUpdate {
	fsu.mutation.ResetTotalThermicTime()
	fsu.mutation.SetTotalThermicTime(i)
	return fsu
}

// SetNillableTotalThermicTime sets the "totalThermicTime" field if the given value is not nil.
func (fsu *FlightStatisticUpdate) SetNillableTotalThermicTime(i *int) *FlightStatisticUpdate {
	if i != nil {
		fsu.SetTotalThermicTime(*i)
	}
	return fsu
}

// AddTotalThermicTime adds i to the "totalThermicTime" field.
func (fsu *FlightStatisticUpdate) AddTotalThermicTime(i int) *FlightStatisticUpdate {
	fsu.mutation.AddTotalThermicTime(i)
	return fsu
}

// SetTotalFlightTime sets the "totalFlightTime" field.
func (fsu *FlightStatisticUpdate) SetTotalFlightTime(i int) *FlightStatisticUpdate {
	fsu.mutation.ResetTotalFlightTime()
	fsu.mutation.SetTotalFlightTime(i)
	return fsu
}

// SetNillableTotalFlightTime sets the "totalFlightTime" field if the given value is not nil.
func (fsu *FlightStatisticUpdate) SetNillableTotalFlightTime(i *int) *FlightStatisticUpdate {
	if i != nil {
		fsu.SetTotalFlightTime(*i)
	}
	return fsu
}

// AddTotalFlightTime adds i to the "totalFlightTime" field.
func (fsu *FlightStatisticUpdate) AddTotalFlightTime(i int) *FlightStatisticUpdate {
	fsu.mutation.AddTotalFlightTime(i)
	return fsu
}

// SetMaxClimb sets the "maxClimb" field.
func (fsu *FlightStatisticUpdate) SetMaxClimb(i int) *FlightStatisticUpdate {
	fsu.mutation.ResetMaxClimb()
	fsu.mutation.SetMaxClimb(i)
	return fsu
}

// SetNillableMaxClimb sets the "maxClimb" field if the given value is not nil.
func (fsu *FlightStatisticUpdate) SetNillableMaxClimb(i *int) *FlightStatisticUpdate {
	if i != nil {
		fsu.SetMaxClimb(*i)
	}
	return fsu
}

// AddMaxClimb adds i to the "maxClimb" field.
func (fsu *FlightStatisticUpdate) AddMaxClimb(i int) *FlightStatisticUpdate {
	fsu.mutation.AddMaxClimb(i)
	return fsu
}

// SetMaxClimbRate sets the "maxClimbRate" field.
func (fsu *FlightStatisticUpdate) SetMaxClimbRate(f float64) *FlightStatisticUpdate {
	fsu.mutation.ResetMaxClimbRate()
	fsu.mutation.SetMaxClimbRate(f)
	return fsu
}

// SetNillableMaxClimbRate sets the "maxClimbRate" field if the given value is not nil.
func (fsu *FlightStatisticUpdate) SetNillableMaxClimbRate(f *float64) *FlightStatisticUpdate {
	if f != nil {
		fsu.SetMaxClimbRate(*f)
	}
	return fsu
}

// AddMaxClimbRate adds f to the "maxClimbRate" field.
func (fsu *FlightStatisticUpdate) AddMaxClimbRate(f float64) *FlightStatisticUpdate {
	fsu.mutation.AddMaxClimbRate(f)
	return fsu
}

// SetTotalClimb sets the "totalClimb" field.
func (fsu *FlightStatisticUpdate) SetTotalClimb(i int) *FlightStatisticUpdate {
	fsu.mutation.ResetTotalClimb()
	fsu.mutation.SetTotalClimb(i)
	return fsu
}

// SetNillableTotalClimb sets the "totalClimb" field if the given value is not nil.
func (fsu *FlightStatisticUpdate) SetNillableTotalClimb(i *int) *FlightStatisticUpdate {
	if i != nil {
		fsu.SetTotalClimb(*i)
	}
	return fsu
}

// AddTotalClimb adds i to the "totalClimb" field.
func (fsu *FlightStatisticUpdate) AddTotalClimb(i int) *FlightStatisticUpdate {
	fsu.mutation.AddTotalClimb(i)
	return fsu
}

// SetAverageClimbRate sets the "averageClimbRate" field.
func (fsu *FlightStatisticUpdate) SetAverageClimbRate(f float64) *FlightStatisticUpdate {
	fsu.mutation.ResetAverageClimbRate()
	fsu.mutation.SetAverageClimbRate(f)
	return fsu
}

// SetNillableAverageClimbRate sets the "averageClimbRate" field if the given value is not nil.
func (fsu *FlightStatisticUpdate) SetNillableAverageClimbRate(f *float64) *FlightStatisticUpdate {
	if f != nil {
		fsu.SetAverageClimbRate(*f)
	}
	return fsu
}

// AddAverageClimbRate adds f to the "averageClimbRate" field.
func (fsu *FlightStatisticUpdate) AddAverageClimbRate(f float64) *FlightStatisticUpdate {
	fsu.mutation.AddAverageClimbRate(f)
	return fsu
}

// SetNumberOfThermals sets the "numberOfThermals" field.
func (fsu *FlightStatisticUpdate) SetNumberOfThermals(i int) *FlightStatisticUpdate {
	fsu.mutation.ResetNumberOfThermals()
	fsu.mutation.SetNumberOfThermals(i)
	return fsu
}

// SetNillableNumberOfThermals sets the "numberOfThermals" field if the given value is not nil.
func (fsu *FlightStatisticUpdate) SetNillableNumberOfThermals(i *int) *FlightStatisticUpdate {
	if i != nil {
		fsu.SetNumberOfThermals(*i)
	}
	return fsu
}

// AddNumberOfThermals adds i to the "numberOfThermals" field.
func (fsu *FlightStatisticUpdate) AddNumberOfThermals(i int) *FlightStatisticUpdate {
	fsu.mutation.AddNumberOfThermals(i)
	return fsu
}

// SetPercentageThermic sets the "percentageThermic" field.
func (fsu *FlightStatisticUpdate) SetPercentageThermic(f float64) *FlightStatisticUpdate {
	fsu.mutation.ResetPercentageThermic()
	fsu.mutation.SetPercentageThermic(f)
	return fsu
}

// SetNillablePercentageThermic sets the "percentageThermic" field if the given value is not nil.
func (fsu *FlightStatisticUpdate) SetNillablePercentageThermic(f *float64) *FlightStatisticUpdate {
	if f != nil {
		fsu.SetPercentageThermic(*f)
	}
	return fsu
}

// AddPercentageThermic adds f to the "percentageThermic" field.
func (fsu *FlightStatisticUpdate) AddPercentageThermic(f float64) *FlightStatisticUpdate {
	fsu.mutation.AddPercentageThermic(f)
	return fsu
}

// SetMaxAltitude sets the "maxAltitude" field.
func (fsu *FlightStatisticUpdate) SetMaxAltitude(i int) *FlightStatisticUpdate {
	fsu.mutation.ResetMaxAltitude()
	fsu.mutation.SetMaxAltitude(i)
	return fsu
}

// SetNillableMaxAltitude sets the "maxAltitude" field if the given value is not nil.
func (fsu *FlightStatisticUpdate) SetNillableMaxAltitude(i *int) *FlightStatisticUpdate {
	if i != nil {
		fsu.SetMaxAltitude(*i)
	}
	return fsu
}

// AddMaxAltitude adds i to the "maxAltitude" field.
func (fsu *FlightStatisticUpdate) AddMaxAltitude(i int) *FlightStatisticUpdate {
	fsu.mutation.AddMaxAltitude(i)
	return fsu
}

// SetTotalDistance sets the "totalDistance" field.
func (fsu *FlightStatisticUpdate) SetTotalDistance(i int) *FlightStatisticUpdate {
	fsu.mutation.ResetTotalDistance()
	fsu.mutation.SetTotalDistance(i)
	return fsu
}

// SetNillableTotalDistance sets the "totalDistance" field if the given value is not nil.
func (fsu *FlightStatisticUpdate) SetNillableTotalDistance(i *int) *FlightStatisticUpdate {
	if i != nil {
		fsu.SetTotalDistance(*i)
	}
	return fsu
}

// AddTotalDistance adds i to the "totalDistance" field.
func (fsu *FlightStatisticUpdate) AddTotalDistance(i int) *FlightStatisticUpdate {
	fsu.mutation.AddTotalDistance(i)
	return fsu
}

// SetFlightID sets the "flight" edge to the Flight entity by ID.
func (fsu *FlightStatisticUpdate) SetFlightID(id int) *FlightStatisticUpdate {
	fsu.mutation.SetFlightID(id)
	return fsu
}

// SetNillableFlightID sets the "flight" edge to the Flight entity by ID if the given value is not nil.
func (fsu *FlightStatisticUpdate) SetNillableFlightID(id *int) *FlightStatisticUpdate {
	if id != nil {
		fsu = fsu.SetFlightID(*id)
	}
	return fsu
}

// SetFlight sets the "flight" edge to the Flight entity.
func (fsu *FlightStatisticUpdate) SetFlight(f *Flight) *FlightStatisticUpdate {
	return fsu.SetFlightID(f.ID)
}

// Mutation returns the FlightStatisticMutation object of the builder.
func (fsu *FlightStatisticUpdate) Mutation() *FlightStatisticMutation {
	return fsu.mutation
}

// ClearFlight clears the "flight" edge to the Flight entity.
func (fsu *FlightStatisticUpdate) ClearFlight() *FlightStatisticUpdate {
	fsu.mutation.ClearFlight()
	return fsu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (fsu *FlightStatisticUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, fsu.sqlSave, fsu.mutation, fsu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (fsu *FlightStatisticUpdate) SaveX(ctx context.Context) int {
	affected, err := fsu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (fsu *FlightStatisticUpdate) Exec(ctx context.Context) error {
	_, err := fsu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fsu *FlightStatisticUpdate) ExecX(ctx context.Context) {
	if err := fsu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (fsu *FlightStatisticUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(flightstatistic.Table, flightstatistic.Columns, sqlgraph.NewFieldSpec(flightstatistic.FieldID, field.TypeInt))
	if ps := fsu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fsu.mutation.TotalThermicTime(); ok {
		_spec.SetField(flightstatistic.FieldTotalThermicTime, field.TypeInt, value)
	}
	if value, ok := fsu.mutation.AddedTotalThermicTime(); ok {
		_spec.AddField(flightstatistic.FieldTotalThermicTime, field.TypeInt, value)
	}
	if value, ok := fsu.mutation.TotalFlightTime(); ok {
		_spec.SetField(flightstatistic.FieldTotalFlightTime, field.TypeInt, value)
	}
	if value, ok := fsu.mutation.AddedTotalFlightTime(); ok {
		_spec.AddField(flightstatistic.FieldTotalFlightTime, field.TypeInt, value)
	}
	if value, ok := fsu.mutation.MaxClimb(); ok {
		_spec.SetField(flightstatistic.FieldMaxClimb, field.TypeInt, value)
	}
	if value, ok := fsu.mutation.AddedMaxClimb(); ok {
		_spec.AddField(flightstatistic.FieldMaxClimb, field.TypeInt, value)
	}
	if value, ok := fsu.mutation.MaxClimbRate(); ok {
		_spec.SetField(flightstatistic.FieldMaxClimbRate, field.TypeFloat64, value)
	}
	if value, ok := fsu.mutation.AddedMaxClimbRate(); ok {
		_spec.AddField(flightstatistic.FieldMaxClimbRate, field.TypeFloat64, value)
	}
	if value, ok := fsu.mutation.TotalClimb(); ok {
		_spec.SetField(flightstatistic.FieldTotalClimb, field.TypeInt, value)
	}
	if value, ok := fsu.mutation.AddedTotalClimb(); ok {
		_spec.AddField(flightstatistic.FieldTotalClimb, field.TypeInt, value)
	}
	if value, ok := fsu.mutation.AverageClimbRate(); ok {
		_spec.SetField(flightstatistic.FieldAverageClimbRate, field.TypeFloat64, value)
	}
	if value, ok := fsu.mutation.AddedAverageClimbRate(); ok {
		_spec.AddField(flightstatistic.FieldAverageClimbRate, field.TypeFloat64, value)
	}
	if value, ok := fsu.mutation.NumberOfThermals(); ok {
		_spec.SetField(flightstatistic.FieldNumberOfThermals, field.TypeInt, value)
	}
	if value, ok := fsu.mutation.AddedNumberOfThermals(); ok {
		_spec.AddField(flightstatistic.FieldNumberOfThermals, field.TypeInt, value)
	}
	if value, ok := fsu.mutation.PercentageThermic(); ok {
		_spec.SetField(flightstatistic.FieldPercentageThermic, field.TypeFloat64, value)
	}
	if value, ok := fsu.mutation.AddedPercentageThermic(); ok {
		_spec.AddField(flightstatistic.FieldPercentageThermic, field.TypeFloat64, value)
	}
	if value, ok := fsu.mutation.MaxAltitude(); ok {
		_spec.SetField(flightstatistic.FieldMaxAltitude, field.TypeInt, value)
	}
	if value, ok := fsu.mutation.AddedMaxAltitude(); ok {
		_spec.AddField(flightstatistic.FieldMaxAltitude, field.TypeInt, value)
	}
	if value, ok := fsu.mutation.TotalDistance(); ok {
		_spec.SetField(flightstatistic.FieldTotalDistance, field.TypeInt, value)
	}
	if value, ok := fsu.mutation.AddedTotalDistance(); ok {
		_spec.AddField(flightstatistic.FieldTotalDistance, field.TypeInt, value)
	}
	if fsu.mutation.FlightCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   flightstatistic.FlightTable,
			Columns: []string{flightstatistic.FlightColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flight.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fsu.mutation.FlightIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   flightstatistic.FlightTable,
			Columns: []string{flightstatistic.FlightColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flight.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, fsu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{flightstatistic.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	fsu.mutation.done = true
	return n, nil
}

// FlightStatisticUpdateOne is the builder for updating a single FlightStatistic entity.
type FlightStatisticUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FlightStatisticMutation
}

// SetTotalThermicTime sets the "totalThermicTime" field.
func (fsuo *FlightStatisticUpdateOne) SetTotalThermicTime(i int) *FlightStatisticUpdateOne {
	fsuo.mutation.ResetTotalThermicTime()
	fsuo.mutation.SetTotalThermicTime(i)
	return fsuo
}

// SetNillableTotalThermicTime sets the "totalThermicTime" field if the given value is not nil.
func (fsuo *FlightStatisticUpdateOne) SetNillableTotalThermicTime(i *int) *FlightStatisticUpdateOne {
	if i != nil {
		fsuo.SetTotalThermicTime(*i)
	}
	return fsuo
}

// AddTotalThermicTime adds i to the "totalThermicTime" field.
func (fsuo *FlightStatisticUpdateOne) AddTotalThermicTime(i int) *FlightStatisticUpdateOne {
	fsuo.mutation.AddTotalThermicTime(i)
	return fsuo
}

// SetTotalFlightTime sets the "totalFlightTime" field.
func (fsuo *FlightStatisticUpdateOne) SetTotalFlightTime(i int) *FlightStatisticUpdateOne {
	fsuo.mutation.ResetTotalFlightTime()
	fsuo.mutation.SetTotalFlightTime(i)
	return fsuo
}

// SetNillableTotalFlightTime sets the "totalFlightTime" field if the given value is not nil.
func (fsuo *FlightStatisticUpdateOne) SetNillableTotalFlightTime(i *int) *FlightStatisticUpdateOne {
	if i != nil {
		fsuo.SetTotalFlightTime(*i)
	}
	return fsuo
}

// AddTotalFlightTime adds i to the "totalFlightTime" field.
func (fsuo *FlightStatisticUpdateOne) AddTotalFlightTime(i int) *FlightStatisticUpdateOne {
	fsuo.mutation.AddTotalFlightTime(i)
	return fsuo
}

// SetMaxClimb sets the "maxClimb" field.
func (fsuo *FlightStatisticUpdateOne) SetMaxClimb(i int) *FlightStatisticUpdateOne {
	fsuo.mutation.ResetMaxClimb()
	fsuo.mutation.SetMaxClimb(i)
	return fsuo
}

// SetNillableMaxClimb sets the "maxClimb" field if the given value is not nil.
func (fsuo *FlightStatisticUpdateOne) SetNillableMaxClimb(i *int) *FlightStatisticUpdateOne {
	if i != nil {
		fsuo.SetMaxClimb(*i)
	}
	return fsuo
}

// AddMaxClimb adds i to the "maxClimb" field.
func (fsuo *FlightStatisticUpdateOne) AddMaxClimb(i int) *FlightStatisticUpdateOne {
	fsuo.mutation.AddMaxClimb(i)
	return fsuo
}

// SetMaxClimbRate sets the "maxClimbRate" field.
func (fsuo *FlightStatisticUpdateOne) SetMaxClimbRate(f float64) *FlightStatisticUpdateOne {
	fsuo.mutation.ResetMaxClimbRate()
	fsuo.mutation.SetMaxClimbRate(f)
	return fsuo
}

// SetNillableMaxClimbRate sets the "maxClimbRate" field if the given value is not nil.
func (fsuo *FlightStatisticUpdateOne) SetNillableMaxClimbRate(f *float64) *FlightStatisticUpdateOne {
	if f != nil {
		fsuo.SetMaxClimbRate(*f)
	}
	return fsuo
}

// AddMaxClimbRate adds f to the "maxClimbRate" field.
func (fsuo *FlightStatisticUpdateOne) AddMaxClimbRate(f float64) *FlightStatisticUpdateOne {
	fsuo.mutation.AddMaxClimbRate(f)
	return fsuo
}

// SetTotalClimb sets the "totalClimb" field.
func (fsuo *FlightStatisticUpdateOne) SetTotalClimb(i int) *FlightStatisticUpdateOne {
	fsuo.mutation.ResetTotalClimb()
	fsuo.mutation.SetTotalClimb(i)
	return fsuo
}

// SetNillableTotalClimb sets the "totalClimb" field if the given value is not nil.
func (fsuo *FlightStatisticUpdateOne) SetNillableTotalClimb(i *int) *FlightStatisticUpdateOne {
	if i != nil {
		fsuo.SetTotalClimb(*i)
	}
	return fsuo
}

// AddTotalClimb adds i to the "totalClimb" field.
func (fsuo *FlightStatisticUpdateOne) AddTotalClimb(i int) *FlightStatisticUpdateOne {
	fsuo.mutation.AddTotalClimb(i)
	return fsuo
}

// SetAverageClimbRate sets the "averageClimbRate" field.
func (fsuo *FlightStatisticUpdateOne) SetAverageClimbRate(f float64) *FlightStatisticUpdateOne {
	fsuo.mutation.ResetAverageClimbRate()
	fsuo.mutation.SetAverageClimbRate(f)
	return fsuo
}

// SetNillableAverageClimbRate sets the "averageClimbRate" field if the given value is not nil.
func (fsuo *FlightStatisticUpdateOne) SetNillableAverageClimbRate(f *float64) *FlightStatisticUpdateOne {
	if f != nil {
		fsuo.SetAverageClimbRate(*f)
	}
	return fsuo
}

// AddAverageClimbRate adds f to the "averageClimbRate" field.
func (fsuo *FlightStatisticUpdateOne) AddAverageClimbRate(f float64) *FlightStatisticUpdateOne {
	fsuo.mutation.AddAverageClimbRate(f)
	return fsuo
}

// SetNumberOfThermals sets the "numberOfThermals" field.
func (fsuo *FlightStatisticUpdateOne) SetNumberOfThermals(i int) *FlightStatisticUpdateOne {
	fsuo.mutation.ResetNumberOfThermals()
	fsuo.mutation.SetNumberOfThermals(i)
	return fsuo
}

// SetNillableNumberOfThermals sets the "numberOfThermals" field if the given value is not nil.
func (fsuo *FlightStatisticUpdateOne) SetNillableNumberOfThermals(i *int) *FlightStatisticUpdateOne {
	if i != nil {
		fsuo.SetNumberOfThermals(*i)
	}
	return fsuo
}

// AddNumberOfThermals adds i to the "numberOfThermals" field.
func (fsuo *FlightStatisticUpdateOne) AddNumberOfThermals(i int) *FlightStatisticUpdateOne {
	fsuo.mutation.AddNumberOfThermals(i)
	return fsuo
}

// SetPercentageThermic sets the "percentageThermic" field.
func (fsuo *FlightStatisticUpdateOne) SetPercentageThermic(f float64) *FlightStatisticUpdateOne {
	fsuo.mutation.ResetPercentageThermic()
	fsuo.mutation.SetPercentageThermic(f)
	return fsuo
}

// SetNillablePercentageThermic sets the "percentageThermic" field if the given value is not nil.
func (fsuo *FlightStatisticUpdateOne) SetNillablePercentageThermic(f *float64) *FlightStatisticUpdateOne {
	if f != nil {
		fsuo.SetPercentageThermic(*f)
	}
	return fsuo
}

// AddPercentageThermic adds f to the "percentageThermic" field.
func (fsuo *FlightStatisticUpdateOne) AddPercentageThermic(f float64) *FlightStatisticUpdateOne {
	fsuo.mutation.AddPercentageThermic(f)
	return fsuo
}

// SetMaxAltitude sets the "maxAltitude" field.
func (fsuo *FlightStatisticUpdateOne) SetMaxAltitude(i int) *FlightStatisticUpdateOne {
	fsuo.mutation.ResetMaxAltitude()
	fsuo.mutation.SetMaxAltitude(i)
	return fsuo
}

// SetNillableMaxAltitude sets the "maxAltitude" field if the given value is not nil.
func (fsuo *FlightStatisticUpdateOne) SetNillableMaxAltitude(i *int) *FlightStatisticUpdateOne {
	if i != nil {
		fsuo.SetMaxAltitude(*i)
	}
	return fsuo
}

// AddMaxAltitude adds i to the "maxAltitude" field.
func (fsuo *FlightStatisticUpdateOne) AddMaxAltitude(i int) *FlightStatisticUpdateOne {
	fsuo.mutation.AddMaxAltitude(i)
	return fsuo
}

// SetTotalDistance sets the "totalDistance" field.
func (fsuo *FlightStatisticUpdateOne) SetTotalDistance(i int) *FlightStatisticUpdateOne {
	fsuo.mutation.ResetTotalDistance()
	fsuo.mutation.SetTotalDistance(i)
	return fsuo
}

// SetNillableTotalDistance sets the "totalDistance" field if the given value is not nil.
func (fsuo *FlightStatisticUpdateOne) SetNillableTotalDistance(i *int) *FlightStatisticUpdateOne {
	if i != nil {
		fsuo.SetTotalDistance(*i)
	}
	return fsuo
}

// AddTotalDistance adds i to the "totalDistance" field.
func (fsuo *FlightStatisticUpdateOne) AddTotalDistance(i int) *FlightStatisticUpdateOne {
	fsuo.mutation.AddTotalDistance(i)
	return fsuo
}

// SetFlightID sets the "flight" edge to the Flight entity by ID.
func (fsuo *FlightStatisticUpdateOne) SetFlightID(id int) *FlightStatisticUpdateOne {
	fsuo.mutation.SetFlightID(id)
	return fsuo
}

// SetNillableFlightID sets the "flight" edge to the Flight entity by ID if the given value is not nil.
func (fsuo *FlightStatisticUpdateOne) SetNillableFlightID(id *int) *FlightStatisticUpdateOne {
	if id != nil {
		fsuo = fsuo.SetFlightID(*id)
	}
	return fsuo
}

// SetFlight sets the "flight" edge to the Flight entity.
func (fsuo *FlightStatisticUpdateOne) SetFlight(f *Flight) *FlightStatisticUpdateOne {
	return fsuo.SetFlightID(f.ID)
}

// Mutation returns the FlightStatisticMutation object of the builder.
func (fsuo *FlightStatisticUpdateOne) Mutation() *FlightStatisticMutation {
	return fsuo.mutation
}

// ClearFlight clears the "flight" edge to the Flight entity.
func (fsuo *FlightStatisticUpdateOne) ClearFlight() *FlightStatisticUpdateOne {
	fsuo.mutation.ClearFlight()
	return fsuo
}

// Where appends a list predicates to the FlightStatisticUpdate builder.
func (fsuo *FlightStatisticUpdateOne) Where(ps ...predicate.FlightStatistic) *FlightStatisticUpdateOne {
	fsuo.mutation.Where(ps...)
	return fsuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (fsuo *FlightStatisticUpdateOne) Select(field string, fields ...string) *FlightStatisticUpdateOne {
	fsuo.fields = append([]string{field}, fields...)
	return fsuo
}

// Save executes the query and returns the updated FlightStatistic entity.
func (fsuo *FlightStatisticUpdateOne) Save(ctx context.Context) (*FlightStatistic, error) {
	return withHooks(ctx, fsuo.sqlSave, fsuo.mutation, fsuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (fsuo *FlightStatisticUpdateOne) SaveX(ctx context.Context) *FlightStatistic {
	node, err := fsuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (fsuo *FlightStatisticUpdateOne) Exec(ctx context.Context) error {
	_, err := fsuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fsuo *FlightStatisticUpdateOne) ExecX(ctx context.Context) {
	if err := fsuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (fsuo *FlightStatisticUpdateOne) sqlSave(ctx context.Context) (_node *FlightStatistic, err error) {
	_spec := sqlgraph.NewUpdateSpec(flightstatistic.Table, flightstatistic.Columns, sqlgraph.NewFieldSpec(flightstatistic.FieldID, field.TypeInt))
	id, ok := fsuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FlightStatistic.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := fsuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, flightstatistic.FieldID)
		for _, f := range fields {
			if !flightstatistic.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != flightstatistic.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := fsuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fsuo.mutation.TotalThermicTime(); ok {
		_spec.SetField(flightstatistic.FieldTotalThermicTime, field.TypeInt, value)
	}
	if value, ok := fsuo.mutation.AddedTotalThermicTime(); ok {
		_spec.AddField(flightstatistic.FieldTotalThermicTime, field.TypeInt, value)
	}
	if value, ok := fsuo.mutation.TotalFlightTime(); ok {
		_spec.SetField(flightstatistic.FieldTotalFlightTime, field.TypeInt, value)
	}
	if value, ok := fsuo.mutation.AddedTotalFlightTime(); ok {
		_spec.AddField(flightstatistic.FieldTotalFlightTime, field.TypeInt, value)
	}
	if value, ok := fsuo.mutation.MaxClimb(); ok {
		_spec.SetField(flightstatistic.FieldMaxClimb, field.TypeInt, value)
	}
	if value, ok := fsuo.mutation.AddedMaxClimb(); ok {
		_spec.AddField(flightstatistic.FieldMaxClimb, field.TypeInt, value)
	}
	if value, ok := fsuo.mutation.MaxClimbRate(); ok {
		_spec.SetField(flightstatistic.FieldMaxClimbRate, field.TypeFloat64, value)
	}
	if value, ok := fsuo.mutation.AddedMaxClimbRate(); ok {
		_spec.AddField(flightstatistic.FieldMaxClimbRate, field.TypeFloat64, value)
	}
	if value, ok := fsuo.mutation.TotalClimb(); ok {
		_spec.SetField(flightstatistic.FieldTotalClimb, field.TypeInt, value)
	}
	if value, ok := fsuo.mutation.AddedTotalClimb(); ok {
		_spec.AddField(flightstatistic.FieldTotalClimb, field.TypeInt, value)
	}
	if value, ok := fsuo.mutation.AverageClimbRate(); ok {
		_spec.SetField(flightstatistic.FieldAverageClimbRate, field.TypeFloat64, value)
	}
	if value, ok := fsuo.mutation.AddedAverageClimbRate(); ok {
		_spec.AddField(flightstatistic.FieldAverageClimbRate, field.TypeFloat64, value)
	}
	if value, ok := fsuo.mutation.NumberOfThermals(); ok {
		_spec.SetField(flightstatistic.FieldNumberOfThermals, field.TypeInt, value)
	}
	if value, ok := fsuo.mutation.AddedNumberOfThermals(); ok {
		_spec.AddField(flightstatistic.FieldNumberOfThermals, field.TypeInt, value)
	}
	if value, ok := fsuo.mutation.PercentageThermic(); ok {
		_spec.SetField(flightstatistic.FieldPercentageThermic, field.TypeFloat64, value)
	}
	if value, ok := fsuo.mutation.AddedPercentageThermic(); ok {
		_spec.AddField(flightstatistic.FieldPercentageThermic, field.TypeFloat64, value)
	}
	if value, ok := fsuo.mutation.MaxAltitude(); ok {
		_spec.SetField(flightstatistic.FieldMaxAltitude, field.TypeInt, value)
	}
	if value, ok := fsuo.mutation.AddedMaxAltitude(); ok {
		_spec.AddField(flightstatistic.FieldMaxAltitude, field.TypeInt, value)
	}
	if value, ok := fsuo.mutation.TotalDistance(); ok {
		_spec.SetField(flightstatistic.FieldTotalDistance, field.TypeInt, value)
	}
	if value, ok := fsuo.mutation.AddedTotalDistance(); ok {
		_spec.AddField(flightstatistic.FieldTotalDistance, field.TypeInt, value)
	}
	if fsuo.mutation.FlightCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   flightstatistic.FlightTable,
			Columns: []string{flightstatistic.FlightColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flight.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fsuo.mutation.FlightIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   flightstatistic.FlightTable,
			Columns: []string{flightstatistic.FlightColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flight.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &FlightStatistic{config: fsuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, fsuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{flightstatistic.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	fsuo.mutation.done = true
	return _node, nil
}
