// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/AurelienS/cigare/internal/storage/ent/flight"
	"github.com/AurelienS/cigare/internal/storage/ent/flightstatistic"
)

// FlightStatistic is the model entity for the FlightStatistic schema.
type FlightStatistic struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// TotalThermicTime holds the value of the "totalThermicTime" field.
	TotalThermicTime int `json:"totalThermicTime,omitempty"`
	// TotalFlightTime holds the value of the "totalFlightTime" field.
	TotalFlightTime int `json:"totalFlightTime,omitempty"`
	// MaxClimb holds the value of the "maxClimb" field.
	MaxClimb int `json:"maxClimb,omitempty"`
	// MaxClimbRate holds the value of the "maxClimbRate" field.
	MaxClimbRate float64 `json:"maxClimbRate,omitempty"`
	// TotalClimb holds the value of the "totalClimb" field.
	TotalClimb int `json:"totalClimb,omitempty"`
	// AverageClimbRate holds the value of the "averageClimbRate" field.
	AverageClimbRate float64 `json:"averageClimbRate,omitempty"`
	// NumberOfThermals holds the value of the "numberOfThermals" field.
	NumberOfThermals int `json:"numberOfThermals,omitempty"`
	// PercentageThermic holds the value of the "percentageThermic" field.
	PercentageThermic float64 `json:"percentageThermic,omitempty"`
	// MaxAltitude holds the value of the "maxAltitude" field.
	MaxAltitude int `json:"maxAltitude,omitempty"`
	// TotalDistance holds the value of the "totalDistance" field.
	TotalDistance int `json:"totalDistance,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FlightStatisticQuery when eager-loading is set.
	Edges            FlightStatisticEdges `json:"edges"`
	flight_statistic *int
	selectValues     sql.SelectValues
}

// FlightStatisticEdges holds the relations/edges for other nodes in the graph.
type FlightStatisticEdges struct {
	// Flight holds the value of the flight edge.
	Flight *Flight `json:"flight,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// FlightOrErr returns the Flight value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e FlightStatisticEdges) FlightOrErr() (*Flight, error) {
	if e.loadedTypes[0] {
		if e.Flight == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: flight.Label}
		}
		return e.Flight, nil
	}
	return nil, &NotLoadedError{edge: "flight"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FlightStatistic) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case flightstatistic.FieldMaxClimbRate, flightstatistic.FieldAverageClimbRate, flightstatistic.FieldPercentageThermic:
			values[i] = new(sql.NullFloat64)
		case flightstatistic.FieldID, flightstatistic.FieldTotalThermicTime, flightstatistic.FieldTotalFlightTime, flightstatistic.FieldMaxClimb, flightstatistic.FieldTotalClimb, flightstatistic.FieldNumberOfThermals, flightstatistic.FieldMaxAltitude, flightstatistic.FieldTotalDistance:
			values[i] = new(sql.NullInt64)
		case flightstatistic.ForeignKeys[0]: // flight_statistic
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FlightStatistic fields.
func (fs *FlightStatistic) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case flightstatistic.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			fs.ID = int(value.Int64)
		case flightstatistic.FieldTotalThermicTime:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field totalThermicTime", values[i])
			} else if value.Valid {
				fs.TotalThermicTime = int(value.Int64)
			}
		case flightstatistic.FieldTotalFlightTime:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field totalFlightTime", values[i])
			} else if value.Valid {
				fs.TotalFlightTime = int(value.Int64)
			}
		case flightstatistic.FieldMaxClimb:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field maxClimb", values[i])
			} else if value.Valid {
				fs.MaxClimb = int(value.Int64)
			}
		case flightstatistic.FieldMaxClimbRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field maxClimbRate", values[i])
			} else if value.Valid {
				fs.MaxClimbRate = value.Float64
			}
		case flightstatistic.FieldTotalClimb:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field totalClimb", values[i])
			} else if value.Valid {
				fs.TotalClimb = int(value.Int64)
			}
		case flightstatistic.FieldAverageClimbRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field averageClimbRate", values[i])
			} else if value.Valid {
				fs.AverageClimbRate = value.Float64
			}
		case flightstatistic.FieldNumberOfThermals:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field numberOfThermals", values[i])
			} else if value.Valid {
				fs.NumberOfThermals = int(value.Int64)
			}
		case flightstatistic.FieldPercentageThermic:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field percentageThermic", values[i])
			} else if value.Valid {
				fs.PercentageThermic = value.Float64
			}
		case flightstatistic.FieldMaxAltitude:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field maxAltitude", values[i])
			} else if value.Valid {
				fs.MaxAltitude = int(value.Int64)
			}
		case flightstatistic.FieldTotalDistance:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field totalDistance", values[i])
			} else if value.Valid {
				fs.TotalDistance = int(value.Int64)
			}
		case flightstatistic.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field flight_statistic", value)
			} else if value.Valid {
				fs.flight_statistic = new(int)
				*fs.flight_statistic = int(value.Int64)
			}
		default:
			fs.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the FlightStatistic.
// This includes values selected through modifiers, order, etc.
func (fs *FlightStatistic) Value(name string) (ent.Value, error) {
	return fs.selectValues.Get(name)
}

// QueryFlight queries the "flight" edge of the FlightStatistic entity.
func (fs *FlightStatistic) QueryFlight() *FlightQuery {
	return NewFlightStatisticClient(fs.config).QueryFlight(fs)
}

// Update returns a builder for updating this FlightStatistic.
// Note that you need to call FlightStatistic.Unwrap() before calling this method if this FlightStatistic
// was returned from a transaction, and the transaction was committed or rolled back.
func (fs *FlightStatistic) Update() *FlightStatisticUpdateOne {
	return NewFlightStatisticClient(fs.config).UpdateOne(fs)
}

// Unwrap unwraps the FlightStatistic entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (fs *FlightStatistic) Unwrap() *FlightStatistic {
	_tx, ok := fs.config.driver.(*txDriver)
	if !ok {
		panic("ent: FlightStatistic is not a transactional entity")
	}
	fs.config.driver = _tx.drv
	return fs
}

// String implements the fmt.Stringer.
func (fs *FlightStatistic) String() string {
	var builder strings.Builder
	builder.WriteString("FlightStatistic(")
	builder.WriteString(fmt.Sprintf("id=%v, ", fs.ID))
	builder.WriteString("totalThermicTime=")
	builder.WriteString(fmt.Sprintf("%v", fs.TotalThermicTime))
	builder.WriteString(", ")
	builder.WriteString("totalFlightTime=")
	builder.WriteString(fmt.Sprintf("%v", fs.TotalFlightTime))
	builder.WriteString(", ")
	builder.WriteString("maxClimb=")
	builder.WriteString(fmt.Sprintf("%v", fs.MaxClimb))
	builder.WriteString(", ")
	builder.WriteString("maxClimbRate=")
	builder.WriteString(fmt.Sprintf("%v", fs.MaxClimbRate))
	builder.WriteString(", ")
	builder.WriteString("totalClimb=")
	builder.WriteString(fmt.Sprintf("%v", fs.TotalClimb))
	builder.WriteString(", ")
	builder.WriteString("averageClimbRate=")
	builder.WriteString(fmt.Sprintf("%v", fs.AverageClimbRate))
	builder.WriteString(", ")
	builder.WriteString("numberOfThermals=")
	builder.WriteString(fmt.Sprintf("%v", fs.NumberOfThermals))
	builder.WriteString(", ")
	builder.WriteString("percentageThermic=")
	builder.WriteString(fmt.Sprintf("%v", fs.PercentageThermic))
	builder.WriteString(", ")
	builder.WriteString("maxAltitude=")
	builder.WriteString(fmt.Sprintf("%v", fs.MaxAltitude))
	builder.WriteString(", ")
	builder.WriteString("totalDistance=")
	builder.WriteString(fmt.Sprintf("%v", fs.TotalDistance))
	builder.WriteByte(')')
	return builder.String()
}

// FlightStatistics is a parsable slice of FlightStatistic.
type FlightStatistics []*FlightStatistic
