// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/AurelienS/cigare/internal/storage/ent/flight"
	"github.com/AurelienS/cigare/internal/storage/ent/flightstatistic"
	"github.com/AurelienS/cigare/internal/storage/ent/predicate"
	"github.com/AurelienS/cigare/internal/storage/ent/user"
)

// FlightUpdate is the builder for updating Flight entities.
type FlightUpdate struct {
	config
	hooks    []Hook
	mutation *FlightMutation
}

// Where appends a list predicates to the FlightUpdate builder.
func (fu *FlightUpdate) Where(ps ...predicate.Flight) *FlightUpdate {
	fu.mutation.Where(ps...)
	return fu
}

// SetDate sets the "date" field.
func (fu *FlightUpdate) SetDate(t time.Time) *FlightUpdate {
	fu.mutation.SetDate(t)
	return fu
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (fu *FlightUpdate) SetNillableDate(t *time.Time) *FlightUpdate {
	if t != nil {
		fu.SetDate(*t)
	}
	return fu
}

// SetTakeoffLocation sets the "takeoffLocation" field.
func (fu *FlightUpdate) SetTakeoffLocation(s string) *FlightUpdate {
	fu.mutation.SetTakeoffLocation(s)
	return fu
}

// SetNillableTakeoffLocation sets the "takeoffLocation" field if the given value is not nil.
func (fu *FlightUpdate) SetNillableTakeoffLocation(s *string) *FlightUpdate {
	if s != nil {
		fu.SetTakeoffLocation(*s)
	}
	return fu
}

// SetIgcFilePath sets the "igcFilePath" field.
func (fu *FlightUpdate) SetIgcFilePath(s string) *FlightUpdate {
	fu.mutation.SetIgcFilePath(s)
	return fu
}

// SetNillableIgcFilePath sets the "igcFilePath" field if the given value is not nil.
func (fu *FlightUpdate) SetNillableIgcFilePath(s *string) *FlightUpdate {
	if s != nil {
		fu.SetIgcFilePath(*s)
	}
	return fu
}

// SetPilotID sets the "pilot" edge to the User entity by ID.
func (fu *FlightUpdate) SetPilotID(id int) *FlightUpdate {
	fu.mutation.SetPilotID(id)
	return fu
}

// SetNillablePilotID sets the "pilot" edge to the User entity by ID if the given value is not nil.
func (fu *FlightUpdate) SetNillablePilotID(id *int) *FlightUpdate {
	if id != nil {
		fu = fu.SetPilotID(*id)
	}
	return fu
}

// SetPilot sets the "pilot" edge to the User entity.
func (fu *FlightUpdate) SetPilot(u *User) *FlightUpdate {
	return fu.SetPilotID(u.ID)
}

// SetStatisticID sets the "statistic" edge to the FlightStatistic entity by ID.
func (fu *FlightUpdate) SetStatisticID(id int) *FlightUpdate {
	fu.mutation.SetStatisticID(id)
	return fu
}

// SetNillableStatisticID sets the "statistic" edge to the FlightStatistic entity by ID if the given value is not nil.
func (fu *FlightUpdate) SetNillableStatisticID(id *int) *FlightUpdate {
	if id != nil {
		fu = fu.SetStatisticID(*id)
	}
	return fu
}

// SetStatistic sets the "statistic" edge to the FlightStatistic entity.
func (fu *FlightUpdate) SetStatistic(f *FlightStatistic) *FlightUpdate {
	return fu.SetStatisticID(f.ID)
}

// Mutation returns the FlightMutation object of the builder.
func (fu *FlightUpdate) Mutation() *FlightMutation {
	return fu.mutation
}

// ClearPilot clears the "pilot" edge to the User entity.
func (fu *FlightUpdate) ClearPilot() *FlightUpdate {
	fu.mutation.ClearPilot()
	return fu
}

// ClearStatistic clears the "statistic" edge to the FlightStatistic entity.
func (fu *FlightUpdate) ClearStatistic() *FlightUpdate {
	fu.mutation.ClearStatistic()
	return fu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (fu *FlightUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, fu.sqlSave, fu.mutation, fu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (fu *FlightUpdate) SaveX(ctx context.Context) int {
	affected, err := fu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (fu *FlightUpdate) Exec(ctx context.Context) error {
	_, err := fu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fu *FlightUpdate) ExecX(ctx context.Context) {
	if err := fu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (fu *FlightUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(flight.Table, flight.Columns, sqlgraph.NewFieldSpec(flight.FieldID, field.TypeInt))
	if ps := fu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fu.mutation.Date(); ok {
		_spec.SetField(flight.FieldDate, field.TypeTime, value)
	}
	if value, ok := fu.mutation.TakeoffLocation(); ok {
		_spec.SetField(flight.FieldTakeoffLocation, field.TypeString, value)
	}
	if value, ok := fu.mutation.IgcFilePath(); ok {
		_spec.SetField(flight.FieldIgcFilePath, field.TypeString, value)
	}
	if fu.mutation.PilotCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flight.PilotTable,
			Columns: []string{flight.PilotColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fu.mutation.PilotIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flight.PilotTable,
			Columns: []string{flight.PilotColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if fu.mutation.StatisticCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   flight.StatisticTable,
			Columns: []string{flight.StatisticColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flightstatistic.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fu.mutation.StatisticIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   flight.StatisticTable,
			Columns: []string{flight.StatisticColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flightstatistic.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, fu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{flight.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	fu.mutation.done = true
	return n, nil
}

// FlightUpdateOne is the builder for updating a single Flight entity.
type FlightUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FlightMutation
}

// SetDate sets the "date" field.
func (fuo *FlightUpdateOne) SetDate(t time.Time) *FlightUpdateOne {
	fuo.mutation.SetDate(t)
	return fuo
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (fuo *FlightUpdateOne) SetNillableDate(t *time.Time) *FlightUpdateOne {
	if t != nil {
		fuo.SetDate(*t)
	}
	return fuo
}

// SetTakeoffLocation sets the "takeoffLocation" field.
func (fuo *FlightUpdateOne) SetTakeoffLocation(s string) *FlightUpdateOne {
	fuo.mutation.SetTakeoffLocation(s)
	return fuo
}

// SetNillableTakeoffLocation sets the "takeoffLocation" field if the given value is not nil.
func (fuo *FlightUpdateOne) SetNillableTakeoffLocation(s *string) *FlightUpdateOne {
	if s != nil {
		fuo.SetTakeoffLocation(*s)
	}
	return fuo
}

// SetIgcFilePath sets the "igcFilePath" field.
func (fuo *FlightUpdateOne) SetIgcFilePath(s string) *FlightUpdateOne {
	fuo.mutation.SetIgcFilePath(s)
	return fuo
}

// SetNillableIgcFilePath sets the "igcFilePath" field if the given value is not nil.
func (fuo *FlightUpdateOne) SetNillableIgcFilePath(s *string) *FlightUpdateOne {
	if s != nil {
		fuo.SetIgcFilePath(*s)
	}
	return fuo
}

// SetPilotID sets the "pilot" edge to the User entity by ID.
func (fuo *FlightUpdateOne) SetPilotID(id int) *FlightUpdateOne {
	fuo.mutation.SetPilotID(id)
	return fuo
}

// SetNillablePilotID sets the "pilot" edge to the User entity by ID if the given value is not nil.
func (fuo *FlightUpdateOne) SetNillablePilotID(id *int) *FlightUpdateOne {
	if id != nil {
		fuo = fuo.SetPilotID(*id)
	}
	return fuo
}

// SetPilot sets the "pilot" edge to the User entity.
func (fuo *FlightUpdateOne) SetPilot(u *User) *FlightUpdateOne {
	return fuo.SetPilotID(u.ID)
}

// SetStatisticID sets the "statistic" edge to the FlightStatistic entity by ID.
func (fuo *FlightUpdateOne) SetStatisticID(id int) *FlightUpdateOne {
	fuo.mutation.SetStatisticID(id)
	return fuo
}

// SetNillableStatisticID sets the "statistic" edge to the FlightStatistic entity by ID if the given value is not nil.
func (fuo *FlightUpdateOne) SetNillableStatisticID(id *int) *FlightUpdateOne {
	if id != nil {
		fuo = fuo.SetStatisticID(*id)
	}
	return fuo
}

// SetStatistic sets the "statistic" edge to the FlightStatistic entity.
func (fuo *FlightUpdateOne) SetStatistic(f *FlightStatistic) *FlightUpdateOne {
	return fuo.SetStatisticID(f.ID)
}

// Mutation returns the FlightMutation object of the builder.
func (fuo *FlightUpdateOne) Mutation() *FlightMutation {
	return fuo.mutation
}

// ClearPilot clears the "pilot" edge to the User entity.
func (fuo *FlightUpdateOne) ClearPilot() *FlightUpdateOne {
	fuo.mutation.ClearPilot()
	return fuo
}

// ClearStatistic clears the "statistic" edge to the FlightStatistic entity.
func (fuo *FlightUpdateOne) ClearStatistic() *FlightUpdateOne {
	fuo.mutation.ClearStatistic()
	return fuo
}

// Where appends a list predicates to the FlightUpdate builder.
func (fuo *FlightUpdateOne) Where(ps ...predicate.Flight) *FlightUpdateOne {
	fuo.mutation.Where(ps...)
	return fuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (fuo *FlightUpdateOne) Select(field string, fields ...string) *FlightUpdateOne {
	fuo.fields = append([]string{field}, fields...)
	return fuo
}

// Save executes the query and returns the updated Flight entity.
func (fuo *FlightUpdateOne) Save(ctx context.Context) (*Flight, error) {
	return withHooks(ctx, fuo.sqlSave, fuo.mutation, fuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (fuo *FlightUpdateOne) SaveX(ctx context.Context) *Flight {
	node, err := fuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (fuo *FlightUpdateOne) Exec(ctx context.Context) error {
	_, err := fuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fuo *FlightUpdateOne) ExecX(ctx context.Context) {
	if err := fuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (fuo *FlightUpdateOne) sqlSave(ctx context.Context) (_node *Flight, err error) {
	_spec := sqlgraph.NewUpdateSpec(flight.Table, flight.Columns, sqlgraph.NewFieldSpec(flight.FieldID, field.TypeInt))
	id, ok := fuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Flight.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := fuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, flight.FieldID)
		for _, f := range fields {
			if !flight.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != flight.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := fuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fuo.mutation.Date(); ok {
		_spec.SetField(flight.FieldDate, field.TypeTime, value)
	}
	if value, ok := fuo.mutation.TakeoffLocation(); ok {
		_spec.SetField(flight.FieldTakeoffLocation, field.TypeString, value)
	}
	if value, ok := fuo.mutation.IgcFilePath(); ok {
		_spec.SetField(flight.FieldIgcFilePath, field.TypeString, value)
	}
	if fuo.mutation.PilotCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flight.PilotTable,
			Columns: []string{flight.PilotColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fuo.mutation.PilotIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flight.PilotTable,
			Columns: []string{flight.PilotColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if fuo.mutation.StatisticCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   flight.StatisticTable,
			Columns: []string{flight.StatisticColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flightstatistic.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fuo.mutation.StatisticIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   flight.StatisticTable,
			Columns: []string{flight.StatisticColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flightstatistic.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Flight{config: fuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, fuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{flight.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	fuo.mutation.done = true
	return _node, nil
}
