// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/AurelienS/cigare/internal/storage/ent/flight"
	"github.com/AurelienS/cigare/internal/storage/ent/flightstatistic"
)

// FlightStatisticCreate is the builder for creating a FlightStatistic entity.
type FlightStatisticCreate struct {
	config
	mutation *FlightStatisticMutation
	hooks    []Hook
}

// SetTotalThermicTime sets the "totalThermicTime" field.
func (fsc *FlightStatisticCreate) SetTotalThermicTime(i int) *FlightStatisticCreate {
	fsc.mutation.SetTotalThermicTime(i)
	return fsc
}

// SetTotalFlightTime sets the "totalFlightTime" field.
func (fsc *FlightStatisticCreate) SetTotalFlightTime(i int) *FlightStatisticCreate {
	fsc.mutation.SetTotalFlightTime(i)
	return fsc
}

// SetMaxClimb sets the "maxClimb" field.
func (fsc *FlightStatisticCreate) SetMaxClimb(i int) *FlightStatisticCreate {
	fsc.mutation.SetMaxClimb(i)
	return fsc
}

// SetMaxClimbRate sets the "maxClimbRate" field.
func (fsc *FlightStatisticCreate) SetMaxClimbRate(f float64) *FlightStatisticCreate {
	fsc.mutation.SetMaxClimbRate(f)
	return fsc
}

// SetTotalClimb sets the "totalClimb" field.
func (fsc *FlightStatisticCreate) SetTotalClimb(i int) *FlightStatisticCreate {
	fsc.mutation.SetTotalClimb(i)
	return fsc
}

// SetAverageClimbRate sets the "averageClimbRate" field.
func (fsc *FlightStatisticCreate) SetAverageClimbRate(f float64) *FlightStatisticCreate {
	fsc.mutation.SetAverageClimbRate(f)
	return fsc
}

// SetNumberOfThermals sets the "numberOfThermals" field.
func (fsc *FlightStatisticCreate) SetNumberOfThermals(i int) *FlightStatisticCreate {
	fsc.mutation.SetNumberOfThermals(i)
	return fsc
}

// SetPercentageThermic sets the "percentageThermic" field.
func (fsc *FlightStatisticCreate) SetPercentageThermic(f float64) *FlightStatisticCreate {
	fsc.mutation.SetPercentageThermic(f)
	return fsc
}

// SetMaxAltitude sets the "maxAltitude" field.
func (fsc *FlightStatisticCreate) SetMaxAltitude(i int) *FlightStatisticCreate {
	fsc.mutation.SetMaxAltitude(i)
	return fsc
}

// SetFlightID sets the "flight" edge to the Flight entity by ID.
func (fsc *FlightStatisticCreate) SetFlightID(id int) *FlightStatisticCreate {
	fsc.mutation.SetFlightID(id)
	return fsc
}

// SetNillableFlightID sets the "flight" edge to the Flight entity by ID if the given value is not nil.
func (fsc *FlightStatisticCreate) SetNillableFlightID(id *int) *FlightStatisticCreate {
	if id != nil {
		fsc = fsc.SetFlightID(*id)
	}
	return fsc
}

// SetFlight sets the "flight" edge to the Flight entity.
func (fsc *FlightStatisticCreate) SetFlight(f *Flight) *FlightStatisticCreate {
	return fsc.SetFlightID(f.ID)
}

// Mutation returns the FlightStatisticMutation object of the builder.
func (fsc *FlightStatisticCreate) Mutation() *FlightStatisticMutation {
	return fsc.mutation
}

// Save creates the FlightStatistic in the database.
func (fsc *FlightStatisticCreate) Save(ctx context.Context) (*FlightStatistic, error) {
	return withHooks(ctx, fsc.sqlSave, fsc.mutation, fsc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (fsc *FlightStatisticCreate) SaveX(ctx context.Context) *FlightStatistic {
	v, err := fsc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (fsc *FlightStatisticCreate) Exec(ctx context.Context) error {
	_, err := fsc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fsc *FlightStatisticCreate) ExecX(ctx context.Context) {
	if err := fsc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (fsc *FlightStatisticCreate) check() error {
	if _, ok := fsc.mutation.TotalThermicTime(); !ok {
		return &ValidationError{Name: "totalThermicTime", err: errors.New(`ent: missing required field "FlightStatistic.totalThermicTime"`)}
	}
	if _, ok := fsc.mutation.TotalFlightTime(); !ok {
		return &ValidationError{Name: "totalFlightTime", err: errors.New(`ent: missing required field "FlightStatistic.totalFlightTime"`)}
	}
	if _, ok := fsc.mutation.MaxClimb(); !ok {
		return &ValidationError{Name: "maxClimb", err: errors.New(`ent: missing required field "FlightStatistic.maxClimb"`)}
	}
	if _, ok := fsc.mutation.MaxClimbRate(); !ok {
		return &ValidationError{Name: "maxClimbRate", err: errors.New(`ent: missing required field "FlightStatistic.maxClimbRate"`)}
	}
	if _, ok := fsc.mutation.TotalClimb(); !ok {
		return &ValidationError{Name: "totalClimb", err: errors.New(`ent: missing required field "FlightStatistic.totalClimb"`)}
	}
	if _, ok := fsc.mutation.AverageClimbRate(); !ok {
		return &ValidationError{Name: "averageClimbRate", err: errors.New(`ent: missing required field "FlightStatistic.averageClimbRate"`)}
	}
	if _, ok := fsc.mutation.NumberOfThermals(); !ok {
		return &ValidationError{Name: "numberOfThermals", err: errors.New(`ent: missing required field "FlightStatistic.numberOfThermals"`)}
	}
	if _, ok := fsc.mutation.PercentageThermic(); !ok {
		return &ValidationError{Name: "percentageThermic", err: errors.New(`ent: missing required field "FlightStatistic.percentageThermic"`)}
	}
	if _, ok := fsc.mutation.MaxAltitude(); !ok {
		return &ValidationError{Name: "maxAltitude", err: errors.New(`ent: missing required field "FlightStatistic.maxAltitude"`)}
	}
	return nil
}

func (fsc *FlightStatisticCreate) sqlSave(ctx context.Context) (*FlightStatistic, error) {
	if err := fsc.check(); err != nil {
		return nil, err
	}
	_node, _spec := fsc.createSpec()
	if err := sqlgraph.CreateNode(ctx, fsc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	fsc.mutation.id = &_node.ID
	fsc.mutation.done = true
	return _node, nil
}

func (fsc *FlightStatisticCreate) createSpec() (*FlightStatistic, *sqlgraph.CreateSpec) {
	var (
		_node = &FlightStatistic{config: fsc.config}
		_spec = sqlgraph.NewCreateSpec(flightstatistic.Table, sqlgraph.NewFieldSpec(flightstatistic.FieldID, field.TypeInt))
	)
	if value, ok := fsc.mutation.TotalThermicTime(); ok {
		_spec.SetField(flightstatistic.FieldTotalThermicTime, field.TypeInt, value)
		_node.TotalThermicTime = value
	}
	if value, ok := fsc.mutation.TotalFlightTime(); ok {
		_spec.SetField(flightstatistic.FieldTotalFlightTime, field.TypeInt, value)
		_node.TotalFlightTime = value
	}
	if value, ok := fsc.mutation.MaxClimb(); ok {
		_spec.SetField(flightstatistic.FieldMaxClimb, field.TypeInt, value)
		_node.MaxClimb = value
	}
	if value, ok := fsc.mutation.MaxClimbRate(); ok {
		_spec.SetField(flightstatistic.FieldMaxClimbRate, field.TypeFloat64, value)
		_node.MaxClimbRate = value
	}
	if value, ok := fsc.mutation.TotalClimb(); ok {
		_spec.SetField(flightstatistic.FieldTotalClimb, field.TypeInt, value)
		_node.TotalClimb = value
	}
	if value, ok := fsc.mutation.AverageClimbRate(); ok {
		_spec.SetField(flightstatistic.FieldAverageClimbRate, field.TypeFloat64, value)
		_node.AverageClimbRate = value
	}
	if value, ok := fsc.mutation.NumberOfThermals(); ok {
		_spec.SetField(flightstatistic.FieldNumberOfThermals, field.TypeInt, value)
		_node.NumberOfThermals = value
	}
	if value, ok := fsc.mutation.PercentageThermic(); ok {
		_spec.SetField(flightstatistic.FieldPercentageThermic, field.TypeFloat64, value)
		_node.PercentageThermic = value
	}
	if value, ok := fsc.mutation.MaxAltitude(); ok {
		_spec.SetField(flightstatistic.FieldMaxAltitude, field.TypeInt, value)
		_node.MaxAltitude = value
	}
	if nodes := fsc.mutation.FlightIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   flightstatistic.FlightTable,
			Columns: []string{flightstatistic.FlightColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flight.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.flight_statistic = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// FlightStatisticCreateBulk is the builder for creating many FlightStatistic entities in bulk.
type FlightStatisticCreateBulk struct {
	config
	err      error
	builders []*FlightStatisticCreate
}

// Save creates the FlightStatistic entities in the database.
func (fscb *FlightStatisticCreateBulk) Save(ctx context.Context) ([]*FlightStatistic, error) {
	if fscb.err != nil {
		return nil, fscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(fscb.builders))
	nodes := make([]*FlightStatistic, len(fscb.builders))
	mutators := make([]Mutator, len(fscb.builders))
	for i := range fscb.builders {
		func(i int, root context.Context) {
			builder := fscb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FlightStatisticMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, fscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, fscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, fscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (fscb *FlightStatisticCreateBulk) SaveX(ctx context.Context) []*FlightStatistic {
	v, err := fscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (fscb *FlightStatisticCreateBulk) Exec(ctx context.Context) error {
	_, err := fscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fscb *FlightStatisticCreateBulk) ExecX(ctx context.Context) {
	if err := fscb.Exec(ctx); err != nil {
		panic(err)
	}
}
