// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/AurelienS/cigare/internal/storage/ent/squad"
)

// Squad is the model entity for the Squad schema.
type Squad struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// CreatedAt holds the value of the "createdAt" field.
	CreatedAt time.Time `json:"createdAt,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SquadQuery when eager-loading is set.
	Edges        SquadEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SquadEdges holds the relations/edges for other nodes in the graph.
type SquadEdges struct {
	// Members holds the value of the members edge.
	Members []*User `json:"members,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// MembersOrErr returns the Members value or an error if the edge
// was not loaded in eager-loading.
func (e SquadEdges) MembersOrErr() ([]*User, error) {
	if e.loadedTypes[0] {
		return e.Members, nil
	}
	return nil, &NotLoadedError{edge: "members"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Squad) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case squad.FieldID:
			values[i] = new(sql.NullInt64)
		case squad.FieldName:
			values[i] = new(sql.NullString)
		case squad.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Squad fields.
func (s *Squad) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case squad.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			s.ID = int(value.Int64)
		case squad.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				s.Name = value.String
			}
		case squad.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field createdAt", values[i])
			} else if value.Valid {
				s.CreatedAt = value.Time
			}
		default:
			s.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Squad.
// This includes values selected through modifiers, order, etc.
func (s *Squad) Value(name string) (ent.Value, error) {
	return s.selectValues.Get(name)
}

// QueryMembers queries the "members" edge of the Squad entity.
func (s *Squad) QueryMembers() *UserQuery {
	return NewSquadClient(s.config).QueryMembers(s)
}

// Update returns a builder for updating this Squad.
// Note that you need to call Squad.Unwrap() before calling this method if this Squad
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Squad) Update() *SquadUpdateOne {
	return NewSquadClient(s.config).UpdateOne(s)
}

// Unwrap unwraps the Squad entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (s *Squad) Unwrap() *Squad {
	_tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Squad is not a transactional entity")
	}
	s.config.driver = _tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Squad) String() string {
	var builder strings.Builder
	builder.WriteString("Squad(")
	builder.WriteString(fmt.Sprintf("id=%v, ", s.ID))
	builder.WriteString("name=")
	builder.WriteString(s.Name)
	builder.WriteString(", ")
	builder.WriteString("createdAt=")
	builder.WriteString(s.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Squads is a parsable slice of Squad.
type Squads []*Squad
