// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/AurelienS/cigare/internal/storage/ent/squad"
	"github.com/AurelienS/cigare/internal/storage/ent/user"
)

// SquadCreate is the builder for creating a Squad entity.
type SquadCreate struct {
	config
	mutation *SquadMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (sc *SquadCreate) SetName(s string) *SquadCreate {
	sc.mutation.SetName(s)
	return sc
}

// SetCreatedAt sets the "createdAt" field.
func (sc *SquadCreate) SetCreatedAt(t time.Time) *SquadCreate {
	sc.mutation.SetCreatedAt(t)
	return sc
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (sc *SquadCreate) SetNillableCreatedAt(t *time.Time) *SquadCreate {
	if t != nil {
		sc.SetCreatedAt(*t)
	}
	return sc
}

// AddMemberIDs adds the "members" edge to the User entity by IDs.
func (sc *SquadCreate) AddMemberIDs(ids ...int) *SquadCreate {
	sc.mutation.AddMemberIDs(ids...)
	return sc
}

// AddMembers adds the "members" edges to the User entity.
func (sc *SquadCreate) AddMembers(u ...*User) *SquadCreate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return sc.AddMemberIDs(ids...)
}

// Mutation returns the SquadMutation object of the builder.
func (sc *SquadCreate) Mutation() *SquadMutation {
	return sc.mutation
}

// Save creates the Squad in the database.
func (sc *SquadCreate) Save(ctx context.Context) (*Squad, error) {
	sc.defaults()
	return withHooks(ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *SquadCreate) SaveX(ctx context.Context) *Squad {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *SquadCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *SquadCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sc *SquadCreate) defaults() {
	if _, ok := sc.mutation.CreatedAt(); !ok {
		v := squad.DefaultCreatedAt()
		sc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *SquadCreate) check() error {
	if _, ok := sc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Squad.name"`)}
	}
	if _, ok := sc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "createdAt", err: errors.New(`ent: missing required field "Squad.createdAt"`)}
	}
	return nil
}

func (sc *SquadCreate) sqlSave(ctx context.Context) (*Squad, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *SquadCreate) createSpec() (*Squad, *sqlgraph.CreateSpec) {
	var (
		_node = &Squad{config: sc.config}
		_spec = sqlgraph.NewCreateSpec(squad.Table, sqlgraph.NewFieldSpec(squad.FieldID, field.TypeInt))
	)
	if value, ok := sc.mutation.Name(); ok {
		_spec.SetField(squad.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := sc.mutation.CreatedAt(); ok {
		_spec.SetField(squad.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := sc.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   squad.MembersTable,
			Columns: squad.MembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SquadCreateBulk is the builder for creating many Squad entities in bulk.
type SquadCreateBulk struct {
	config
	err      error
	builders []*SquadCreate
}

// Save creates the Squad entities in the database.
func (scb *SquadCreateBulk) Save(ctx context.Context) ([]*Squad, error) {
	if scb.err != nil {
		return nil, scb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Squad, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SquadMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *SquadCreateBulk) SaveX(ctx context.Context) []*Squad {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *SquadCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *SquadCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
