// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.513
package logbookview

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func setUpChartFlightTimeMonthly(data string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_setUpChartFlightTimeMonthly_e341`,
		Function: `function __templ_setUpChartFlightTimeMonthly_e341(data){const ctx = document.getElementById('chart_flight_time_monthly');
	new Chart(ctx, {
    type: 'line',
    data: {
        labels: ["Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre"],
        datasets: [{
        label: '2022',
        data: [45, 49, 60, 61, 36, 35, 20, 50, 40, 45, 50, 60],
        backgroundColor: 'rgba(54, 162, 235, 0.5)',
        borderColor: 'rgb(54, 162, 235)',
        borderWidth: 1,
        cubicInterpolationMode: 'monotone'
    },
    {
        label: '2023',
        data: [65, 59, 80, 81, 56, 55, 40, 70, 60, 75, 80, 90],
        backgroundColor: 'rgba(255, 99, 132, 0.5)',
        borderColor: 'rgb(255, 99, 132)',
        borderWidth: 1,
        cubicInterpolationMode: 'monotone',
        hidden:true,
    },
    {
        label: '2024',
        data: [65, 59, 80, 81, 56, 55, 40, 70, 60, 75, 80, 90],
        backgroundColor: 'rgba(255, 99, 132, 0.5)',
        borderColor: 'rgb(255, 99, 132)',
        borderWidth: 1,
        cubicInterpolationMode: 'monotone',
        hidden:true,
    },
    {
        label: '2025',
        data: [65, 59, 80, 81, 56, 55, 40, 70, 60, 75, 80, 90],
        backgroundColor: 'rgba(255, 99, 132, 0.5)',
        borderColor: 'rgb(255, 99, 132)',
        borderWidth: 1,
        cubicInterpolationMode: 'monotone',
        hidden:true,
    },
    {
        label: '2026',
        data: [65, 59, 80, 81, 56, 55, 40, 70, 60, 75, 80, 90],
        backgroundColor: 'rgba(255, 99, 132, 0.5)',
        borderColor: 'rgb(255, 99, 132)',
        borderWidth: 1,
        cubicInterpolationMode: 'monotone',
        hidden:true,
    },
    {
        label: '2027',
        data: [65, 59, 80, 81, 56, 55, 40, 70, 60, 75, 80, 90],
        backgroundColor: 'rgba(255, 99, 132, 0.5)',
        borderColor: 'rgb(255, 99, 132)',
        borderWidth: 1,
        cubicInterpolationMode: 'monotone',
        hidden:true,
    },
    {
        label: '2028',
        data: [65, 59, 80, 81, 56, 55, 40, 70, 60, 75, 80, 90],
        backgroundColor: 'rgba(255, 99, 132, 0.5)',
        borderColor: 'rgb(255, 99, 132)',
        borderWidth: 1,
        cubicInterpolationMode: 'monotone',
        hidden:true,
    }]
    },
    options: {
        scales: {
            y: {
                beginAtZero: true
            },

        },
        plugins: {
            legend: {
                display: true,
                position: 'left'
            }
        },
        responsive: true,
        maintainAspectRatio: false,
        animation: {
            duration: 1000
        }
    }
});}`,
		Call:       templ.SafeScript(`__templ_setUpChartFlightTimeMonthly_e341`, data),
		CallInline: templ.SafeScriptInline(`__templ_setUpChartFlightTimeMonthly_e341`, data),
	}
}

func ChartFlightTimeMonthly(data string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<canvas id=\"chart_flight_time_monthly\"></canvas>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = setUpChartFlightTimeMonthly(data).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
